### ISSUE TITLE
PDWS: Workflow Templates

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#154]

**Comment by larshp** [comment]
from @jani80k
"One hint for PDWS, there is an existing functionality by SAP to export Workflows.
LSWDDF70 Form xml_export."

**Comment by christianguenter2** [comment]
We are really eager to implement this and PDTS.  I did several experiments but couldn't figure out how to solve the problem of custom number ranges and internal numbering. E.g. WS9000001 could become WS91000055 in another system. Any idea how to solve this?

**Comment by larshp** [comment]
how does this work with normal SAP transports?

**Comment by christianguenter2** [comment]
I tried to figure out how it works with normal SAP transports, but didn't come far.

**Comment by se38** [comment]
Any news on Workflows / Tasks? Could currently need it ;-)
Do you know how it worked in Saplink? https://app.assembla.com/spaces/saplink-plugins/subversion/source/HEAD/trunk/Workflow

**Comment by larshp** [comment]
dont think so, pull requests welcome :)

**Comment by pokrakam** [comment]
This should not work like the transport system does it as it's meant to be landscape-specific per design. I am happy to do this, but not able to assign.
Also suggest combining with #153 as it's the same object internally.

**Comment by christianguenter2** [comment]
@pokrakam cool, I did some experiments with [PDWS](https://github.com/christianguenter2/abapGit/tree/feature_PDWS) and [PDTS](https://github.com/christianguenter2/abapGit/tree/feature_PDTS) maybe this is of any help for you.

To be able to assign issue to you, I think you need push rights for the abapGit repo.
https://github.com/isaacs/github/issues/100

Maybe @larshp can grant them to you.

**Comment by larshp** [comment]
assigned

**Comment by larshp** [comment]
@pokrakam any luck/progress?

**Comment by pokrakam** [comment]
Working on it, a little time-constrained so only getting in the odd couple of hours on a weekend. 
Not sure the SAPlink logic that Christian copied from ever worked under SAPlink. Rather than butcher it, I went back to square one and tried to dig into the transport system to replicate that function, but spent many hours working out how to debug it. Seems it's triggered by tp from the OS level and refuses to trigger any breakpoints. Can't work out how to catch it and see what it does. Any ideas?
My next step was to go back to crowbaring the 'right' logic into the WF create module.

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/pull/2444 it is the closest we get to the transport system, implementing a similar approach for workflows might work. But rather use the API if its possible

**Comment by pokrakam** [comment]
Agree, the issue is that the API imports a WF into a local one, i.e. assigning a number from your local range. Not idempotent, and you can't copy back and forth between systems. Same goes for HR objects which may or may not be transportable (config setting).

A ToC will keep the numbering intact. This is by design in order to be able to copy WF's between systems without conflict (provided each system has a distinct number range, which is set up via a prefix). IMO this is how abapGit should work.
So I can hack the API, or I can figure out what tp does. I tried that option first. The transport system is a very black box :-)

**Comment by larshp** [comment]
it will break the number ranging? if current number is "1" and we import "2", then SAP standard will determine to use "2". 

What is the typical setup if there are multiple development systems in which work flows are created?

perhaps we can somehow choose to import it to a different number and keep the mapping information, it raises some issues on what to show to the user

**Comment by pokrakam** [comment]
It’s a bit like a namespace + original system concept. A number range with a prefix starting with 9 (customer space) is defined in each dev system. So system A with number 901... won’t conflict with system B using 902... if you transport between them.
Import/Create local -> generate new number in own range. 
Transport -> use original number. This is what we want to do.

Yes it does raise issues if a foreign system uses a conflicting range. But this is the same as importing a same-named class and there are workarounds. Oh, and then there is system-local versioning which is done by the transport system (a good thing!)

**Comment by pokrakam** [comment]
Just in case anyone is wondering, I haven't forgotten. Time constrained by projects until the end of June. If anyone wants to work on it before then feel free, else I'll pick it up again in July.

**Comment by WillianGruber** [comment]
> WF create module

@pokrakam  what is this module?

**Comment by chrismills** [comment]
Was this previously supported in some form? I've recently updated my ABAPGit version (1.101.0) and when I go to an existing repo it's now advising me that PDTS and PDWS objects not supported and wants to remove the existing .pdws.xml and .pdts.xml files from my repo. 

I was having short dumps when i first opened this repository. I found some old classes in a abap git plugins package so not sure if there was some old community unofficial support for these object types?

**Comment by pokrakam** [comment]
How old was this repo? These were never supported in abapGit AFAIK.

Once upon a time there was some incomplete work in SAPlink to get PDTS/WS working. @christianguenter2 had a go at porting this into abapGit, but on his fork. So the only thing I can think of is if you worked with his clone?

Regardless, your XMLs are unlikely to work. I'd be interested to see some of their contents, it may shed some more light.

**Comment by chrismills** [comment]
Hi @pokrakam repo its self not old, created this year, but until recently was using an older abapgit which had the old ZABAPGIT_FULL report name and then updated to the newer ZABAPGIT_STANDALONE more recently as was getting github warnings about the login method and 2FA so needed to update it all. 

Looks like in my system we had a dev version of abap git too at some point so in the upgrade i had to delete a lot of Z classes in $ packages that were for abap git as they weren't compatible with new report.

Never tried to restore the WF objects though, but was happily committing them away along with other code. I'll send you some example code via private message on LinkedIn

Cheers

**Comment by pokrakam** [comment]
Hi @chrismills, the XML was very useful. The key clue was in: 
`<abapGit version="v1.0.0" serializer="ZCL_ABAPGIT_OBJECT_BY_SOBJ" serializer_version="1.0">`
So it was serialised as a standard SOBJ object, I'll look into this a little further.

**Comment by pokrakam** [comment]
OK it was done using the deprecated SOBJ plugin 
https://github.com/abapGit/abapGit-Plugins
You can probably use the plugin if you're importing on the same SAP version as you exported, but otherwise it's at your own risk. SOBJ is just a 'dumb' transport of the table entries that make up a table-based SAP object, whereas PDTS and PDWS will create all the components of a Task and a WF using SAP unofficial APIs.
Note PDTS is live but still has some minor issues (most notably container element texts are missing) and needs the "Experimental features" switched on. I'm still busy with PDWS.

**Comment by chrismills** [comment]
Thanks for looking in to that Mike, good to understand how it was working before. I'll steer clear of the SOBJ since it's been deprecated and instead try the experimental for PDTS and keep an eye out on when PDWS is supported too. Thanks for your work on this, appreciated 😃

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.

**Comment by mbtools** [comment]
Backup of branch `pokrakam/pdws` attached as zip
 
[zcl_abapgit_object_pdws.clas.zip](https://github.com/abapGit/abapGit/files/10933963/zcl_abapgit_object_pdws.clas.zip)
