### ISSUE TITLE
SAJC: Application Job Catalog Entry

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1580]
serialization of SAJC

transaction SAPJ

tables:
APJ_W_JCE_GR
APJ_W_JCE_GR_T
APJ_W_JCE_PAR
APJ_W_JCE_ROOT
APJ_W_JCE_RO_T
APJ_W_JCE_SCT
APJ_W_JCE_SCT_T
APJ_W_JCE_SEQ
APJ_W_JCE_SEQ_T

class: CL_APJ_DT_JOB_CAT_DB_ACCESS + CL_APJ_DT_JOB_CAT_ENTRY

**Comment by larshp** [comment]
retrieve data:

```abap
FORM run RAISING cm_apj_base.

  DATA(lo_controller) = cl_apj_dt_controller=>get_instance( ).

  DATA(li_entity) = lo_controller->if_apj_dt_controller~retrieve_single( VALUE #(
    entity_type    = 'JOB_CAT_ENTRY'
    entity_name    = 'ZFOOBAR'
    entity_version = 0 ) ).

  DATA(lo_entry) = CAST cl_apj_dt_job_cat_entry( li_entity ).

  BREAK-POINT.

ENDFORM.
```

can someone help checking if SAJC objects exists on 702?

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.

**Comment by sandraros** [comment]
I see that the implementation of SAJC is using the SAP AFF format, which only serializes the header table (APJ_W_JCE_ROOT). Sections, groups and parameters are missing (tables APJ_W_JCE_GR, APJ_W_JCE_GR_T, APJ_W_JCE_PAR, APJ_W_JCE_SCT, APJ_W_JCE_SCT_T, APJ_W_JCE_SEQ, APJ_W_JCE_SEQ_T).

Is it possible to change the implementation to extend the AFF format? If yes, I can do it, is there any example or recommendation?

Thank you.
Sandra

**Comment by mbtools** [comment]
@sandraros The AFF JSON is always coming from standard SAP code. If there are issues, please create a message, ticket, or case with SAP 😉

**Comment by sandraros** [comment]
@mbtools Thanks. I have looked more in depth, in fact, it's not only an AFF issue but it also concerns the ABAP system used. For instance, SAJC and SAJT used to exist since 7.50, but the AFF framework is available only since 7.56. If I want to use abapGit in these old systems, does abapGit provide a user exit to make a "custom" serialization/deserialization? NB: I already have code to serialize/deserialize SAJC and SAJT, which is working in trial 7.52 SP04.

**Comment by mbtools** [comment]
Actually yes. You can add the object types via exit to the supported objects. Then provide your own version of zcl_abapgit_object_sa..  The format you create might not work in higher releases where AFF comes into play but that's no secret for you

**Comment by sandraros** [comment]
1. I don't like changing the standard abapGit code (rewriting `zcl_abapgit_object_sajc`) because it could be overwritten by mistake after a pull. That would be great to add a user exit to change the name of the implementation class. For instance, calling the user exit in the method [`create_object` of `ZCL_ABAPGIT_OBJECTS`](https://github.com/abapGit/abapGit/blob/f45425f665aab65099c97bd8eaa981e6b0666050/src/objects/zcl_abapgit_objects.clas.abap#L457).

1. Alternatively, to make everyone benefit of SAJC/SAJT, whatever their ABAP release is, abapGit could propose implementations depending on the ABAP release. Concerning SAJC for instance, there would be three implementations:
   - If the installed AFF framework proposes what the current ABAP release supports, use `zcl_abapgit_object_sajc` (the current class, unchanged).
   - If the installed AFF framework doesn't propose what the current ABAP release supports, use `zcl_abapgit_object_sajc_2`. The code might call `zcl_abapgit_object_sajc` then complete the serialization or deserialization for the Sections, Groups and Parameters.
   - If the installed AFF framework doesn't exist, use `zcl_abapgit_object_sajc_3`. The serialize method would implement something like [this code](https://community.sap.com/t5/technology-blogs-by-members/api-to-create-application-job-catalog-entry-amp-template-before-cl-apj-dt/ba-p/14011757).

Do you think one of these 2 solutions is possible? I'll then create an issue/enhancement request (I could propose the code).

**Comment by mbtools** [comment]
For 10 years we have avoided release-specific versions of abapGit. It all works with one code line; one stand-alone report. 

There are quite a few cases with if logic  to allow for different behaviour depending on release. That would be the preferred solution. 

There's also the option to version the xml formats for an object type which we have used a couple times. 

However, this setup did not take AFF into consideration. The way it's implemented right now does not allow for any alternatives. It's all SAP responsibility. We could/should ask for the downport (via a Note). 

Let's move this to a new issue to get more input
