### ISSUE TITLE
BMFR: Application Component

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#2108]
Transactions SBAC, SBACH02 - SBACH05
Package SDFM
Report SBMCV000 to generate a prefix number range

**Comment by larshp** [comment]
@flaiker are you working on this?

**Comment by flaiker** [comment]
@larshp I am looking into it. Not sure how extensive this object type is yet.

**Comment by flaiker** [comment]
Looking into this again.... Some notes:

- BM = Process Modelling (?)
- BMFR = Application Component = "**F**unction **R**ange"

There are lots of other similar object types (?) I never heard of before. Are these SolMan specific and BMFR is the only one leaking out of it by its assignment in DEVC? I never used Solution Manager or the process modelling stuff myself before.

From `LSF00TOP` (I removed the ones that are already supported or commented with dummy / no responsibility):

```abap
* models
* C_TTYP_PROCESS_TREE  TYPE BMT_TTYP VALUE 'BMPT',    "ok
c_ttyp_eorg_proc_tree TYPE bmt_ttyp VALUE 'BMET',           "ok
c_ttyp_function_range_tree TYPE bmt_ttyp VALUE 'BMHT',      "ok
c_ttyp_comp_fuct_tree TYPE bmt_ttyp VALUE 'BMHF',           "ok
c_ttyp_comp_fuct_tree_31 TYPE bmt_ttyp VALUE 'BMGT',        "ok
c_ttyp_var_fuct_tree_31 TYPE bmt_ttyp VALUE 'BMCT',        "ok
c_ttyp_fun_ass_dia   TYPE bmt_ttyp VALUE 'BMFZ',            "ok
c_ttyp_proc_epc      TYPE bmt_ttyp VALUE 'BMEP',            "ok
c_ttyp_scen_epc      TYPE bmt_ttyp VALUE 'BMSP',  "used only for 3.0
*c_ttyp_integration_model TYPE bmt_ttyp VALUE 'BMIP',        "ok
c_ttyp_group_content TYPE bmt_ttyp VALUE 'BMGC',            "ok
c_ttyp_config_group  TYPE bmt_ttyp VALUE 'BMCG',            "ok
* C_TTYP_FILTER_CONTENT TYPE BMT_TTYP VALUE 'BMFC',    "ok
c_ttyp_proc_sel_mat  TYPE bmt_ttyp VALUE 'BMPM',            "ok
c_ttyp_scen_sel_mat  TYPE bmt_ttyp VALUE 'BMSM',            "ok
c_ttyp_inf_flow_dia  TYPE bmt_ttyp VALUE 'BMID',    "ok pseudo object
c_ttyp_com_dia       TYPE bmt_ttyp VALUE 'BMCD',            "ok
c_ttyp_sorg_dia      TYPE bmt_ttyp VALUE 'BMOR',            "ok
c_ttyp_cust_assign   TYPE bmt_ttyp VALUE 'BMCU',
* objects
c_ttyp_function      TYPE bmt_ttyp VALUE 'BMFU',            "ok
c_ttyp_function_range TYPE bmt_ttyp VALUE 'BMFR',           "ok
c_ttyp_event         TYPE bmt_ttyp VALUE 'BMEV',            "ok
c_ttyp_filter        TYPE bmt_ttyp VALUE 'BMFI',            "ok
c_ttyp_group         TYPE bmt_ttyp VALUE 'BMGR',            "ok
c_ttyp_konf_group    TYPE bmt_ttyp VALUE 'SQAK',
c_ttyp_conf_group    TYPE bmt_ttyp VALUE 'SQAK',
c_ttyp_infoflow      TYPE bmt_ttyp VALUE 'BMIF',            "ok
c_ttyp_scenario      TYPE bmt_ttyp VALUE 'BMSZ',            "ok
c_ttyp_entorgtyp     TYPE bmt_ttyp VALUE 'BMEO',            "ok
c_ttyp_comflow       TYPE bmt_ttyp VALUE 'BMKF',            "ok
c_ttyp_sel           TYPE bmt_ttyp VALUE 'BMSL',    "o.k.
c_ttyp_elementary_function     TYPE bmt_ttyp VALUE 'BMEF',  "o.k.
c_ttyp_global_function_variant TYPE bmt_ttyp VALUE 'BMFV',  "o.k.
c_ttyp_process_component       TYPE bmt_ttyp VALUE 'BMPC',  "o.k.
c_ttyp_global_process_variant  TYPE bmt_ttyp VALUE 'BMPV',  "o.k.
c_ttyp_question                TYPE bmt_ttyp VALUE 'SQAQ',
c_ttyp_visualization_group     TYPE bmt_ttyp VALUE 'BMVG',
c_ttyp_c_bus_scenario          TYPE bmt_ttyp VALUE 'BMBS',
```

Supported by the API (i. e. `BM_OBJECT_GET_DATA` etc.) are:
- BMFR - Function Range
- BMPC - Process Component
- BMEF - Elementary Function
- BMPV - Global Process Variant
- BMFV - Global Function Variant
- BMSV - Scenario Variant
- BMVE - Enterprise Process Area
- BMVS - Process Group
- BMBS - cBusiness Scenario

Though on AS ABAP Developer Edition 752 SP04 the only other ones than BMFR that are delivered in TADIR are one BMPC object and one BMPV object which are in a HCM package (PPAP) that was moved to ABA. Need to check on ERP with HR installed what objects exist there.

Since the API has a generic interface for these I opted for creating a base class which can then should be easily extendable for the other object types.

Number ranges:

Unfortunately the API does not seem to allow for external number assignment, you always get a new number. You need to setup the number ranges beforehand using report `SBMCV000`. There also is a concept of prefixes / namespaces. While there is some internal flag to get external number assignment there seems to be no way to set it anymore. Therefore I think the only reasonable approach is to map an external ID to the internal one in TADIR, like we do for SICF I think. For BMFR this should be the component id (i. e. ZAG-TST-TST), though having duplicate component ids only generates a warning unfortunately. I have no idea if the other object types also have an attribute that is somewhat unique and can be used for this.

**Comment by flaiker** [comment]
On ERP 6.0 EHP 7 the following BM* object types show up in TADIR in addition to BMFR (9828 objects in 81 packages):
- __BMPC__
- __BMPV__
- BMSL
- BMAO
- __BMEF__
- BMEV
- BMEP
- BMFU
- __BMFV__
- BMGR
- BMGT
- BMVG

Only the bold ones are supported by BM_OBJECT_GET_DATA I guess.

**Comment by abap-weasel** [comment]
+1 for BMFR

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
