### ISSUE TITLE
Improvements to diff algorithm

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#2804]
The current diff could use some improvements. It's hard to express clearly, but it often doesn't look like it displays the differences the way humans percieve them and you have to look for them yourself. 

I will have to take some time to make examples, because I probably can't post screenshots with company code and blurring it kinda defeats the purpose.

Some more concrete feedback:
- Highlight parts where a changed line is changed
- Ignore whitespace option
- It should match the github diff as much as possible so it doesn't matter where you review from

Technical:

The diff relies on this FM. I looked around and it's not well documented, I couldn't find explanations for the values of one of the parameters and there still seem to be some unfinished parts. Maybe there are better diff implementations lying around in the basis.
https://github.com/larshp/abapGit/blob/ddcc1ee3c6f4a64b9ffc69030417e839e80b143f/src/utils/zcl_abapgit_diff.clas.abap#L117-L124

https://answers.sap.com/questions/651427/algorithm-longest-common-subsequence-problem-in-ab.html

**Comment by FreHu** [comment]
This week I noticed the diff ignores trailing whitespace, if the object has no other changes you get an empty diff that you can still commit.

I think the diff is rather bad for today's standards and would like to nominate it as a topic for #3946

**Comment by mbtools** [comment]
- [ ] Highlight parts where a changed line is changed

Tricky since it's not text but HTML due to syntax highlighting. I'm working on an HTMLdiff. 

- [ ] Ignore whitespace 
- [ ] Ignore comments 
- [ ] Ignore case

These are standard SAP features (see SE38 > Utilities > Settings > ABAP Editor > Splitscreen) and therefore supported by the SVRS... function. However, switching to `RS_CMP_COMPUTE_DELTA` will not only support these options but also replace most of `ZCL_ABAPGIT_DIFF->RENDER`. 

Q: Should these options work just temporarily when displaying diffs or also impact how the diff status of a file is calculated?

**Comment by mbtools** [comment]
I will get around to "Highlight parts where a changed line is changed" eventually. We can close this
