### ISSUE TITLE
APACK - raw solution ?

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#2892]
Trying to implement APACK for [mockup_loader](https://github.com/sbcgua/mockup_loader/blob/apack/src/zcl_mockup_loader_apack_mnfst.clas.abap) ...

Quite confused, seems like a very raw solution at the moment

  - implemented the manifest, imported it into another system ... but the prerequisite package was not imported. Nor any warnings/errors or whatsoever. :(

Maybe I'm mixing things but there are also other questions (partially discussed in the original PR #2485 but seem to be still open) 

- `zif_apack_manifest` vs `if_apack_manifest` ? - documentation refers to `if` but it is `zif`. This is confusing. Does SAP plans to supply the interface globally ?
- zif_apack_manifest is in $TMP package - how it is supposed to travel along with the package? I know the suggestion is to include it into a normal package and transport further "In case you intend to transport projects". Point is that I most always intend to transport projects :) And this raises a whole bunch of questions to clarify with the system owner: what does this interface mean (is it secure, blah blah) ? which package should it belong to actually ? What to do in case of change - will it occasionally break the production in case of update ? Well maybe discussions with owners are manageable. But the maintainability is very unclear - what would be the flow?
- dependency versions - I understand this is not a package manager. But would be nice at least to specify "version that works" and maybe some notifications during deserialization like "the dependency has version X and the package expect Y, it may be an issue, please be informed :)"

**Comment by SebastianWolf-SAP** [comment]
Yes, it is a very raw solution at the moment. Unfortunately, I haven't had the time to work further on this the last months due to other project assignments. However, now things continue, see also #2894 which marks the first step to your last bullet point (dependency versions).

Unfortunately, the only supported scenario right now is the one explained here: https://developers.sap.com/tutorials/abap-environment-abapgit.html In other words, ZABAPGIT currently only supports the export of APACK manifests, not their proper interpretation for an import. That's why the import didn't take the dependencies into account. I was hoping for some help for the import step in ZABAPGIT (as we are focusing on the Cloud environment (aka Steampunk), but that haven't materialized so far. As soon as the versioned dependencies are there, I might have time for the ZABAPGIT import, but that's uncertain right now... :( Volunteers are always welcome!

The interface `if_apack_manifest` is Steampunk-only right now (and will be for the near future...). So ZABAPGIT will need to use `zif_apack_manifest` for the time being. I'll make the documentation more precise.

Concerning recommendations for `zif_apack_manifest`, for now I'd rather remove the implementation class from the respective transport request as it only serves the purpose a proper Git export and is not needed in follow-up system. Some ideas are in my mind how to handle these implementation classes in a more convenient way, but nothing so far which completely solves the issue AND also doesn't have other side effects.

**Comment by SebastianWolf-SAP** [comment]
And I forgot to mention in case you want to transport it: ZIF_APACK_MANIFEST will only remain a marker interface and changes will only be done in a downward-compatible way...
Probably an easy option to change the package assignment in the settings dialog would be an improvement... Other ideas?

**Comment by DerGuteWolf** [comment]
@SebastianWolf-SAP : Regarding `zif_apack_manifest` vs `if_apack_manifest`: Currently the class implementing the interface is also in the git repo. When I develop onpremise, push there and pull on steampunk, I will get a class with a syntax error, or? Will this be addressed somehow?

**Comment by sbcgua** [comment]
@SebastianWolf-SAP: Imho interface solution is rather unsmooth at the moment. A lot of side effects to take care of. In the original PR there was an idea from @jfilak to use dynamic class naming. Imho this is a fair alternative. Maybe as a fallback: find a class with the interface - not found? - try checking some meta info from `abapgit.xml` or name pattern - if found, try it instead of interface. This could be smoother until `if_apack_manifest` is available in 80% of systems by default

**Comment by SebastianWolf-SAP** [comment]
@DerGuteWolf Yes, some possible solutions are already under investigation. Something like the one @sbcgua proposed is definitely among it. :) However, my time is really limited, so contributions are very welcome in that area in order to speed up things...

**Comment by DerGuteWolf** [comment]
The problem is not only with finding, but once you clone a project with a class with one of the marker interfaces, it will fail if is was originally with the one marker interface, but the cloning is for a platform with the other marker interface.
See also https://github.com/larshp/abapGit/pull/2485#discussion_r319923441 for dynamic class naming problem, but if this is solve, this sounds better to me than those two interfaces...

**Comment by larshp** [comment]
close? question...

**Comment by sbcgua** [comment]
Unless there are other opinions, can be closed. It is in search history anyway.
