### ISSUE TITLE
GETWA_NOT_ASSIGNED in ZCL_ABAPGITP_OBJECT_BY_SOBJ

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/abapGit#3076]
When importing the [matt1as/ABAP-SDK-for-Azure/tree/graph-support](https://github.com/matt1as/ABAP-SDK-for-Azure/tree/graph-support) the system dumps with GETWA_NOT_ASSIGNED in the method import_object of the local class lcl_tlogo_bridge of global class ZCL_ABAPGITP_OBJECT_BY_SOBJ. I've fixed that by adding 
```
    IF <lt_imported_data> IS ASSIGNED.
```
after the line:
```
    ASSIGN <ls_imported_prim_tab_content>-data_tab->* TO <lt_imported_data>.
```
But before I create a pull request I ask for better suggestions.

**Comment by larshp** [comment]
yea, so this is part of https://github.com/larshp/abapGit-Plugins

what is the type of the object causing the error? Would really like to support it native instead of via plugins

**Comment by mbtools** [comment]
Hi Gregor,

I don't get any dump cloning https://github.com/microsoft/ABAP-SDK-for-Azure but error "Object type SUCU not supported, serialize"

There are two SUCU files:
- https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zadf/zsdk%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20s_tabu_dis.sucu.xml
- https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/src/zrest/zres%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20s_tabu_dis.sucu.xml

The first file refers to the wrong serializer:
`<abapGit version="v1.0.0" serializer="ZCL_ABAPGIT_OBJECT_BY_SOBJ" serializer_version="1.0">`
It should be like it's in the second file, since SUCU is supported natively:
`<abapGit version="v1.0.0" serializer="LCL_OBJECT_SUCU" serializer_version="v1.0.0">`

PS: The repo needs a bit of "love", adding files to ignore in abapgit.xml, serializing files with latest version of abapGit to remove some of the many diffs, etc.

**Comment by larshp** [comment]
this is really a problem for MS to fix in their repo, https://github.com/microsoft/ABAP-SDK-for-Azure/issues/89, as SUCU is natively supported by abapGit

https://github.com/microsoft/ABAP-SDK-for-Azure/issues/92

I'll close this issue
