### ISSUE TITLE
SHI6/7: Object types for IMG structure enhancement

### ISSUE THREAD

**Issue by jrodriguez-rc** [abapGit/abapGit#3077]
I tried to include in Git repository an enhancement for IMG structure (S_IMG_EXTENSION) and abapGit doesn't include them, I saw that objects are not supported (object types SHI6 and SHI7)

I got that objects from TR and I saw that aren't only those object types, there are also two tables: TNODEIMG and TNODEIMGT:
![image](https://user-images.githubusercontent.com/56556686/69169024-f57c8600-0af7-11ea-85bc-a829eb69367d.png)

**Comment by jrodriguez-rc** [comment]
These objects are not related directly to the package, so abapGit doesn't find them.

The relationship is to extension (SHI5 object type)

**Comment by jrodriguez-rc** [comment]
I created pull request #3200 to include SHI6 into SHI5.

Include IMG Structure extension sequence data from table TTREES into SHI5 content.
This data is SHI6 type in SOBJ, but it hasn't a TADIR entry, so there is no direct relation to package, it is an additional content from TTREE_EXT

Checking content I saw that there are hierarchy entries (SHI3 - TNODEIMG[T]) related to the extension, maybe a rework is needed to include those entries to SHI5 file and manage there

**Comment by mbtools** [comment]
Program `RS_STREE_OBJECTS_TO_REQ_GET` is used produce consistent transport requests for `SHI3`, `SHI6`, and `SHI7`. This includes the `TABU` entries that are required for the transport (otherwise you get an error when you try to release the transport).

I suggest to add the logic of this program (i.e. function `STREE_INSERT_ALL_IN_TRANSPORT`) to the `SHI3` object class and remove it from `SHI5` (reverse #3200).

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
