### ISSUE TITLE
Support for more BW Objects

### ISSUE THREAD

**Issue by captainabap** [abapGit/abapGit#3162]
Hi,

Abapgit is great. Thank you. I use it for my private ABAP Projects. But for my work, I could need support for the following BW Objects:
- ADSO - Advanced DSOs
- AREA - InfoAreas
- DTPA - DAta Transfer Processes
- ROUT - Routines
- RSDS - DataSources
- TRFN - Transformatio

Is this possible? SAP is still struggling with importing transports of various BW Objects. So it can be very challenging. 

Best regards,
Jörg

**Comment by christianguenter2** [comment]
Sure, we can work on it. But I guess all the main abapGit contriubutors are not working in the BW area, so we need the help of the community. Recently @pawelwiejkut started with the BW objects IOBJ and ODSO. Maybe you can try to implement the serializers for the mentioned object types and we can assist?

**Comment by pawelwiejkut** [comment]
Hello all,
@captainabap for now, I'm working on TRFN, and AREA support so please leave this two to me if you want to contribute. Next I can help with other objects, but personally I don't have access to the BW on/4HANA systems so it will be hard with new objects like ADSO.

**Comment by captainabap** [comment]
Hello, 
thank you for your fast feedback. @pawelwiejkut: It's great news, that you are already  working on AREA and TRFN. I can try ADSO, but it will take some time. 
How is the correct order of the different Object types controlled. E.g InfoObjects must be imported before ADSOs. And TRFN must be imported after ADSOs, right?
And have you also covered AMDP Routines in the TRFN serializing?

**Comment by pawelwiejkut** [comment]
@captainabap, haha it was also one of my questions, so let me answer. Prioritization of objects deserialization is done here: https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_objects.clas.abap#L1040

**Comment by larshp** [comment]
suggest adding a note explaining it in https://docs.abapgit.org/development/serializers.html

**Comment by pawelwiejkut** [comment]
@captainabap Hard to say will AMDP be supported in the first version of TRFN  (can't test on non-HANA). Btw. I have looked at my notes and I saw that for ADSO `cl_rso_adso_api=>create` can be a good start point, but of course, the choice is yours.

**Comment by captainabap** [comment]
@pawelwiejkut Thank you! This ADSO class looks promissing.

**Comment by goalkeeper84** [comment]
HI Guys,
may I also can contribute. I have a BW4 and a 7.5 available to test.

**Comment by goalkeeper84** [comment]
> Hello,
> thank you for your fast feedback. @pawelwiejkut: It's great news, that you are already working on AREA and TRFN. I can try ADSO, but it will take some time.
> How is the correct order of the different Object types controlled. E.g InfoObjects must be imported before ADSOs. And TRFN must be imported after ADSOs, right?

- IOs before ADSOs, InfoSources, CompositeProviders, OpenODS, etc
- ADSOs before TRFN, DTP, Composite
- InfoSources before TRFN, DTP

do you think it is necessary to check the "old" objects as well?

**Comment by goalkeeper84** [comment]
@pawelwiejkut and @captainabap any progresses from your side? should I start with the next objects or is there any open problems with area, trfn, adso?

**Comment by pawelwiejkut** [comment]
@goalkeeper84 , nothing from my side. From my point of view you can proceed with next objects

**Comment by captainabap** [comment]
Funny, that all of us are asking the same first question. ;-)

So i forward, what Pawel wrote some months ago:

> @captainabap <https://github.com/captainabap>, haha it was also one of my
> questions, so let me answer. Prioritization of objects deserialization is
> done here: https://github.com/larshp/abapGit
> /blob/master/src/zcl_abapgit_objects.clas.abap#L1040


Regards,
Jörg

Jörg Brandeis
Rheindammstr. 5
68163 Mannheim
+49 177 5407426 <0177%205407426>


Am Mo., 8. Juni 2020 um 16:57 Uhr schrieb goalkeeper84 <
notifications@github.com>:

**Comment by mbtools** [comment]
Hi Everyone,

I might have mentioned it in another place before, but just some words of caution. 

abapGit has severe limitations when it comes to potentially handling BW objects. BW objects have multiple dependencies, between objects of the same type (ex compounded InfoObjects) or between different types (ex an ABAP include inside a BW transformation that selects data from a database table of a BW DataStore object, which is quite common actually). This is already apparent when you try to install or uninstall one of the test repos like https://github.com/abapGit-tests/IOBJ or https://github.com/abapGit-tests/ODSO. It does not have proper error handling or doesn't work at all. Plus there are mistakes like the one I fixed in https://github.com/larshp/abapGit/pull/3631 or the fact that current code references features like XXL attributes that don't exist in lower releases.

BW itself manages all these dependencies during transport and activation phases (and even then you can run into issues). And then there are release and platform dependencies that one would need to handle... abapGit, however, works on one object at a time and supports release from 7.02 onwards. IMHO, it will not be able to handle any kind of realistic BW scenarios that go beyond the most simple configuration.  

Please do not try to implement classes for all these BW objects. It will end up being a nightmare. 

Marc

PS: There are many more reasons not to go down this path. One would be that there are no BAPIs for creating ADSOs or TRFN and many of the old BAPIs aren't supported on HANA or BW/4HANA. You would risk losing support from SAP if you create or modify objects using other SAP-internal functions of classes

**Comment by mbtools** [comment]
not planned
