### ISSUE TITLE
BRF+ serialization

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#33]
FDT0	FDT/BRFplus: System Application
FDT1	FDT/BRFplus: Customizing Application

**Comment by larshp** [comment]
might be relevant, https://archive.sap.com/documents/docs/DOC-4562

**Comment by abapChaoLiu** [comment]
There are three storage types of BRF+ application.
1. System - entry exists in TADIR with OBJECT = FDT0.
2. Customizing - entry **DOESN'T** exist in TADIR. 
Application name and ID are stored in table FDT_ADMN_0000.
Package is stored by Application ID in table FDT_APPL_0000.
3. Mater Data - always in local package, no need to support.

Any suggestion on how to support Customizing storage type?

**Comment by larshp** [comment]
one solution is to manually add it to a business configuration set, https://github.com/larshp/abapGit/issues/1004

but I'd probably recommend changing the storage type of the BRF+ object to system, this would also reflect which package the object belongs to

**Comment by abapChaoLiu** [comment]
1. SYSTEM type cannot be added to a business configuration set.
2. Changing storage type is not an option. SYSTEM and CUSTOMIZING are two different things.
3. CUSTOMIZING type does have package information in table FDT_APPL_0000.

Is it a good idea to add support for SYSTEM type only? It may cause confusion since there are two different ways to handle BRF+ objects based on their storage types.
