### ISSUE TITLE
Different kind of line-breaks

### ISSUE THREAD

**Issue by germanysources** [abapGit/abapGit#3676]
I ran in multiple errors when `git pull` a remote project and import it as a offline repository. `git` adds carriage return and line feed to the checked-out files on windows.
It would be good, if abapGit supports both type of line-breaks (Unix like line-feed and Windows like carriage-return and line-feed).

**Comment by flaiker** [comment]
What is the current behavior of abapGit? Does it commit the files including CRLF? I'd assume it's just LF.

If I recall correctly the "normal" behavior for git is to commit the files as they are, which coming from linux was just LF. On Windows you usually set the core.autocrlf flag to make git convert the LF line endings to CRLF on checkout and remove the CR on commit so the repo always has just LF (which makes it compatible for developers on different operating systems).

https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings

What operating system are you on? What values have you set for autocrlf? What line endings are committed in the repository that has the errors?

**Comment by flaiker** [comment]
Reading it again: Do you mean you download a repo using git clone, which then adds CR to the line endings in the files and then you ZIP the repo on Windows and try to import that ZIP file into abapGit? As opposed to clicking the download ZIP on GitHub which does not add the CR?

**Comment by germanysources** [comment]
Yes i mean `git clone` a remote repository, zip it and import it into abapGit. I want to implement a function, that abapGit can import files with CRLF as line terminator. If for some other tool sets CRLF as line terminator, we don't get any errors in the import step.

**Comment by mbtools** [comment]
This happened to me as well but I came to the conclusion that it's better to adjust my editor than to make abapGit guess what the user tried to do. For example, there would be also "Mac text format" (just CR), big vs little endian, or different encodings like UTF-16 to deal with... Just a mess.

See https://github.com/mbtools/abapGIT-tests-pcedit for an example with readme to reproduce one facet of the issue.

If we adjust the eol during pull/import, then the files in the online repo or zip still contain a different eol (i.e. binary diff). You would have to push or export to be in sync again. Just makes things more messy. 

It's easily fixed by setting your editor to the proper text format i.e. UNIX UTF-8 (LF) or get an editor that supports https://editorconfig.org/.  I just added the correct format for *.abap to it https://github.com/larshp/abapGit/pull/3679.

**Comment by germanysources** [comment]
@mbtools 
Okay no change to abapGit. I I just want to put some notes in the docs, that LF is the only supported line-break when using zipped repositories.

**Comment by mbtools** [comment]
thx for improving the doc!

**Comment by larshp** [comment]
implementing a rule that can be used in CI, https://github.com/abaplint/abaplint/issues/1270

**Comment by larshp** [comment]
I'll try doing `git config --global core.autocrlf input`
