### ISSUE TITLE
Linter error: class/method not found

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#3940]
Getting several errors from the linter for valid code:
`super class ... not found or contains errors`
`method ... does not exist`

See PR #3942 for an example. The classes and methods exist and the code where the error originally appeared runs fine.

**Comment by larshp** [comment]
thanks, please open abaplint bugs in https://github.com/abaplint/abaplint

abaplint requires information regarding super classes in order to be able to do proper syntax checks, and abaplint runs isolated of the ABAP system. For abapGit https://github.com/abaplint/deps is used https://github.com/abapGit/abapGit/blob/master/abaplint.json#L10 to know extra types

i.e. the error message

> super class "cl_workflow_general_task_def" not found or contains errors

is correct

I'll add the class to deps, https://github.com/abaplint/deps/commit/ffc7a9719ae2c5cde449c928a0136f906b82d726, try again

**Comment by pokrakam** [comment]
OK, it's not always clear where the issue lies, linter or this project's abaplint.json. But now I know where this scenario originates and it's finally all green, thanks 👍
