### ISSUE TITLE
Community Call, November 2020

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3946]
Time: 4th Nov, 15:00 CEST

Duration: 1 hour scheduled

Invitations: Open for all, message me your email address on Slack, and I'll forward you the invite

No recording, but minutes of the meeting will be available afterwards

**Agenda**
* Since last time
* Lets dig into some of the stuff mentioned below

**Comment by mbtools** [comment]
- Code styling (https://github.com/abapGit/abapGit/issues/3741#issuecomment-703296446)
- abapgit.xml + apack to package.json, apm (https://github.com/abapGit/abapGit/issues/2236)

**Comment by sbcgua** [comment]
Just some late night ideas.

Idea 1:
Why not to break down in to some kind of teams by interest. e.g. (just dreaming)
- ui/ux
- serialization
- devops related
- package management 
- ... ???

Then each of such "committees" could choose some direction and tasks to work on, at least strategically. Otherwise everybody ends up doing what they like (which maybe is OK too ... because it is open-source)
E.g. I'd personally be interested in ui/ux, rest api stuff and stuff to simplify custom code deployments.

Idea 2:
Why not to dedicate some part of the next session (or also in writing) to sharing of use cases and "pains" that we meet in our projects/activities. It would also help to cristalizing potential direction of improvements and also would be potentially initiate exchange of experience. (inspired by recent webinar by @esjewett by the way it was a cool event !)

**Comment by mbtools** [comment]
I like both ideas. Certainly no.2. 

It's essential to work on the longevity/maintainability of abapGit. there are currently 29 [refactoring topics](https://github.com/abapGit/abapGit/issues?q=is%3Aissue+is%3Aopen+label%3Arefactoring). I suggest grouping and prioritizing them.

**Comment by larshp** [comment]
* usecase presentation
