### ISSUE TITLE
UI: Long object/file names don't fit screen

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4018]
1440x900 resolution and the status icons are not visible (font-size 12pt):

![image](https://user-images.githubusercontent.com/59966492/95866979-98547900-0d36-11eb-84ae-367983ae7656.png)

Changing to font-size 10pt fixes the issue:

![image](https://user-images.githubusercontent.com/59966492/95867151-d6519d00-0d36-11eb-943d-9457d3ccaffc.png)

What's the best way to make this dynamic (responsive)?

**Comment by sbcgua** [comment]
CSS media - https://developer.mozilla.org/en-US/docs/Web/CSS/@media
though I'm not exactly sure how it works in IE. But worth trying. it should end up in a very simple CSS fix.
however there is one potential obstacle - some of font sizes are absolute (`XXpx`, instead of `%` or `smaller`, `larger`) ... so may need some refactoring.

Alternative 2 (if does not work with IE) is the same but with JS (settings body.font-size = ...). The same issue with relative fonts though. 

Option 3 - rewrite everything to fit 1024px as it was initially. hehe. no. it's bad idea of course. :)

**Comment by mbtools** [comment]
mmm, css media makes it depend on screen resolution. i don't think we want smaller font for smaller screens in general. 

the table width depends on content. line-breaking the filenames doesn't feel right. maybe if filename is longer than x, adding a "small-font" class during render is a solution.

**Comment by sbcgua** [comment]
> css media makes it depend on screen resolution

I thought this is what you proposed ? Actually, Ctrl+Mouse wheel works to simulate this ... or as a final solution by the way ...

> adding a "small-font" class during render is a solution

Then different lines will have different font. This would look ... specific ...

I think it will not solve either. What if the file name yet longer ? Probably there is no perfect solution. Probably there should be some logic to shorten the name visually. E.g. 
`src/monster_p01/subpackage/zcl_abap_example.clas.abap` -> `src/.../zcl_abap_example.clas.abap`, where `...` on hover would show complete file name. Though also not perfect.

**Comment by mbtools** [comment]
I knew about "Ctrl+Mouse wheel" but never thought to use it in abapGit. Genius. Plus you can view many more lines. Thanks!

![image](https://user-images.githubusercontent.com/59966492/95928046-6c64e200-0d8e-11eb-85e4-98d39d87ec07.png)
