### ISSUE TITLE
UI: Sort "Switch origin" by PR number

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4031]
I think sorted descending by PR# would be nicer than this:

![image](https://user-images.githubusercontent.com/59966492/96169619-69820280-0ef0-11eb-8e6f-5f32f5034cbc.png)

**Comment by sbcgua** [comment]
yeap, some ordering would be nice. Or search.
I was initially planning to make it a js palette, even wrote the poc back then - https://github.com/sbcgua/abapGit/tree/js-version-of-pr-enum - but decided to keep it abap for some forgotten reason

**Comment by mbtools** [comment]
I really like the feature. Very helpful. 

Any reason why "switched origin" is ready-for-input in settings?

![image](https://user-images.githubusercontent.com/59966492/96175402-da2d1d00-0ef8-11eb-9a8c-5d78c1d4dbdb.png)

**Comment by sbcgua** [comment]
Not that it was a very grounded decision. But the intuition behind is to give a possibility to reset "Switch - Revert" cycle without going to DB Util (clearing the switched origin field). I think there is room for improvement here. Maybe both should be editable ...

**Comment by mbtools** [comment]
The challenge with the palette might have been how to authenticate to retrieve the fork PRs. 

The "Switch to PR" is ok. Maybe call the reverse "Revert from PR". 

Can we change the settings, so that the original (at the time of repo creation) is always kept and visible in read-only? And the "switch" is ready for input? Then I think we can get rid of the "Change repo" popup as suggested in https://github.com/abapGit/abapGit/issues/3451.

**Comment by sbcgua** [comment]
JS palette: yes, I remembered. It was indeed because of auth + because of hitting API limit with unnecessary requests

"Revert from PR" - mmm, not really. UX-wise it is better to show "where to" are you switching. But in general I think the current wording has room for improvement

Managing remotes: well, I'm sure it is a good subject for a separate issue, to rethink and design it properly. I don't think there is a quick solution. No problem to make origin editable. But straight adding one more remote does not make much sense to me. It should be a more mature solution then. To be able to add remotes flexibly and as many as needed. The "Switch origin" feature would then transform to some kind of "temporary remote". And then "change origin" many can indeed be removed. Something like this.

**Comment by sbcgua** [comment]
Maybe "Switch origin: to PR" -> "Switch to PR branch", "Switch origin: revert" -> "Revert to <usr>/<repo>". And remove "beta"

**Comment by mbtools** [comment]
"Switch to PR Branch" and "Revert to Previous Branch" ?
