### ISSUE TITLE
Cancel authentication dialog after click on master branch causes a crash dump

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#4058]
Hello,

steps to reproduce:

1. Go to overview of the repositories
2. cick on the 'master' branch link for a repository
3. abapGit asks for auth data
4. press Escape
5. Crash dump happens

abapGit v1.100.0

Best Regards,

**Comment by christianguenter2** [comment]
![image](https://user-images.githubusercontent.com/17437789/97033978-780d9100-1564-11eb-88d4-c1992bc86d83.png)

![image](https://user-images.githubusercontent.com/17437789/97033994-7f349f00-1564-11eb-8ac1-283ac8904a34.png)

![image](https://user-images.githubusercontent.com/17437789/97034007-85c31680-1564-11eb-9bcb-5356d799fa58.png)

Seems like a side effect of #3989 because cancelling the auth popup is interpreted as abapGit shutdown and all gui controls are initialized.

![image](https://user-images.githubusercontent.com/17437789/97034106-ab502000-1564-11eb-9343-0f0755e6f846.png)
