### ISSUE TITLE
Checkout commit: additional user interface

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4120]
it must be shown to the user that a commit has been selected

**Comment by larshp** [comment]
@mariusraht2 will you look into this?

**Comment by mariusraht2** [comment]
Yes, will do it

**Comment by mariusraht2** [comment]
Thoughts on this? Think about just changing the commit icon to something that shows that the user selected the commit (commit icon + user/head icon).

**Comment by mbtools** [comment]
The commit icon and hash are grey on grey (intentionally). I suggest to use the same mechanism as for the change log.

![image](https://user-images.githubusercontent.com/59966492/99907876-5f041700-2cad-11eb-969e-c9a8e64a1648.png)

If the commit is checked out, then change the color of the icon and hash. Since color changes are not accessible, the tool tip (title) should be changed as well.

**Comment by EduardoCopat** [comment]
The UI branch indicator could be reused for this:

![image](https://user-images.githubusercontent.com/2248490/102807601-d4394800-4423-11eb-915f-ef7164a3051a.png)

This would be a similar approach to what VSCode does:

![image](https://user-images.githubusercontent.com/2248490/102807621-de5b4680-4423-11eb-9984-33a4a991e6a5.png)

I think this makes sense, since branches are references to commits.

On VSCode, you can't push if you are not in a branch:

![image](https://user-images.githubusercontent.com/2248490/102807752-182c4d00-4424-11eb-9634-5151da7a5380.png)

We could add the same validation.

**Comment by EduardoCopat** [comment]
Implemented at #4349
