### ISSUE TITLE
Community Call, December 2020

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4144]
Time: 7th Dec, 15:00 CEST

Duration: 1 hour scheduled, no recording, in English

Invitations: Open for all, message me your email address on [Slack](https://abapgit-slackinviter.herokuapp.com/), and I'll forward you the invite

**Agenda**

* Alexander, @sbcgua "how we use AG now, what are the intentions and problems"
* JSON writer progress, https://github.com/abapGit/abapGit/pull/4255
* Repo class refactoring, https://github.com/abapGit/abapGit/issues/2127
* Unit testing progress, https://github.com/abapGit/abapGit/pull/4256
* Data serialization progress, https://github.com/abapGit/abapGit/pull/4218
* feel free to add more topics in the comments below

**Comment by mbtools** [comment]
We might want to move a week since it's during TechEd

**Comment by larshp** [comment]
@sbcgua does Monday 7th December work for you?

**Comment by pokrakam** [comment]
Why not change the format a little and make it a TechEd breakout session or something like that?

**Comment by sbcgua** [comment]
> @sbcgua does Monday 7th December work for you?

Looks fine for the moment :)

**Comment by larshp** [comment]
in a week

**Comment by sbcgua** [comment]
OK, plan of my super-duper talk for Monday. To remind the idea: a short talk to share how AG is used in our company and what are the problems/pains (and try keeping it in 10 min so that it is not boring to death)

Our flow

Platform of choise and reasons (very trivial)
Branches or not branches (sadly no for now :( )
Pre commit checks
  - unit tests is a must, no excuse
  - long journey to abaplint-backend (not finished)
    - cool tool but a bit slow
    - pragmas in-code (a wish)
    - easiness of install and maintain, documentation
    - missing 1st priority checks SCI checks in abaplint
      - static exceptions
      - unimplemented methods
    - not very convenient UI (to be improved)

Deployment pains
- zip files only, and wow effect for big corp folks
- deplyment marker (or branches, or forks) - spagetti of client versions
- deployment mode UI: one-by-one (or schedule)
- other system = other serialiazation = always differences (pain)
- maintenance views (auto regen please !)
- BAPI (not supported)
- dependencies tracking (mockup loader, ajson ...)

Deployment demands from clients:
- own SCI rules
- auth checks (abaplint to the resque ?)
- selects/updates tables

**Comment by larshp** [comment]
I'll call for next meeting, scheduled for sometime in Januaray

**Comment by larshp** [comment]
probably Feburary

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/issues/4502
