### ISSUE TITLE
Combine "Pull" and "Reset local (forced pull)"

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4282]
Current issues:
- "pull" automatically imports all objects that are changed only remotely (but not locally). There is no option to select which objects should be pulled.
- "pull" ignores all objects that exist only locally (but not remotely). There is no option to delete the local objects. However, "reset local" allows you to select if objects should be deleted. 
- "pull" and "reset local" let you select objects if they are changed on both sides or have been deleted locally. 
- "reset local" has a user confirmation popup, "pull" does not

Proposal:

Combine both features into "pull" and show **one** selection popup that lists **all** objects with a diff. The popup shall contain the following columns:
- checkbox
- object type
- object name
- current local state (same as in repo view)
- current remote state (same as in repo view)
- comment

The comment shall describe what happens if the object is selected and imported (plus a corresponding icon):
- "update local object" (selected by default)
- "delete local object" (not selected)
 
If the user selects objects to be deleted that exist only locally (so there's no remote backup), then the user shall confirm the deletion in an additional popup.

**Comment by JanisB-AT** [comment]
Tagging #413.

I like the proposal very much, if for no other reason than because it provides rationale for doing the fairly extensive changes needed IMO to enable "selective pull" :) 

By "show one selection popup that lists all objects with a diff", did you mean that the popup should by displayed always, @mbtools? Another possibility were to let the "Pull" proceed with the default selection, and leave the selection popup to "Selective Pull", which could replace "force Pull" in the Advanced menu. The main reason I'm asking is: "selective Pull" would also need to include objects in the status "XA" (objects not existing locally) in the popup...

To enable optional deletion during pull were IMO fairly straightforward: starting point would be "moving" the deletion logic from ZCL_ABAPGIT_SERVICES_GIT->RESET( ) into  ZCL_ABAPGIT_SERVICES_REPO->GUI_DESERIALISE( ). There the popup could be merged with the two already there (overwrite and package overwrite). Because of "package overwrite" the local package would also need to appear on the popup.

Side question: is there any particular reason ZCL_ABAPGIT_POPUPS->POPUP_TO_SELECT_FROM_LIST( ) does not enable user to search and filter the list contents..? Asking because those would seem like obvious things to have, SALV has the functionality, but its not available on the UI (simply because of the choice of PF-STATUS, I suspect)...

It would IMO be nice to have two additional functions on the popup: select/deselect dependencies, but that may be taking it too far...

**Comment by mbtools** [comment]
I like the idea of keeping "pull" as is but replacing "force pull" with "selective pull". I'm thinking now that it's should not be a popup but a page like "staging" where we list all objects with diffs and let the user select what to do. Similar to "stage commit", the "selective pull" could be followed by a confirmation page that shows the selected actions for the user to confirm. 

We could build this apart from existing features and later decide if the old "reset local" is still required (probably not). It would be easier to add new features like "select/deselect dependencies" as well. 

PS: Feel free to do a PR for the popup.

**Comment by sbcgua** [comment]
ref #3705
