### ISSUE TITLE
Issue with error handling in new online dialog

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#4319]
- Use a git host where there is not automatic redirect between user/repo and user/repo.git
- New online
- Enter url without .git
- Press clone
- Get a 404 http error, the clone dialog is still open
- Add .git to url
- Press clone again
- Get error message "Repository user/repo.git is already versioned as ... by ..." and "Package ... is already versioned as ... by ..."

After cancelling the dialog you can see the repo was already created and you need to change the remote there to fix the .git suffix. It is not transparent the repo was created because the 404 error message is issued in the dialog. I also noticed the repo is not added to the favorites.

**Comment by mbtools** [comment]
The DB commit is too early and needs to be moved.

**Comment by mbtools** [comment]
at end of `ZIF_ABAPGIT_REPO_SRV~NEW_ONLINE` there's `ro_repo->find_remote_dot_abapgit( ).` which included the commit. However, in case of exceptions, there might be some implicit commit somewhere rather than a rollback.

**Comment by mbtools** [comment]
More research: the commit is caused by the HTTP communication itself ([implicit db commit](https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abendb_commit.htm)).

In this particular case, the first HTTP call happens in `ZCL_ABAPGIT_GIT_TRANSPORT->FIND_BRANCH`.

The tricky part is that the first HTTP call to gitlab in `find_branch` returns `200 OK`. It's the second call in `upload_pack` that returns `422 error`. 

PS: Test case: `https://gitlab.com/christianguenter/test_enho_clas` 
(`https://gitlab.com/christianguenter/test_enho_clas.git` works fine).
