### ISSUE TITLE
PROG: Program and text elements failing to be created during PULL if there is a syntax error due to missing object

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#4500]
abapGit Version: 1.104.0
ABAP Version: 75E ( S/4HANA ON PREMISE 1909 )

We are using abapGit as part of S/4HANA implementation and major issues are related to removed data elements, table type etc.. This is causing issue for custom programs which are using these missing objects. During the PULL, it is failing to create program for the first PULL and not able to PULL the text elements( Text Symbols, Selection Text ) due to syntax error caused by missing objects in S/4HANA. To replicate the issue, I have created a program which uses custom data element and removed this data element so that we can simulate the scenario. Use the [github ](https://github.com/yellappam/abapgit_prog_text_elements/tree/branch2) and branch branch2 for replicating the issue.

1. Before PULL

![image](https://user-images.githubusercontent.com/29766214/107475615-4aaf2680-6bd9-11eb-9692-35317ac1d053.png)

2. After first PULL, it gives error check inactive objects. However, it hasn't created program at this stage. It would be nice to improve the message here as it hasn't created the program. Or, create the program during first PULL.

![image](https://user-images.githubusercontent.com/29766214/107475716-6dd9d600-6bd9-11eb-8fa2-2217df50f829.png)

3. After second PULL, it created program but didn't import the text elements( Text Symbols, Selection Text ) due to syntax error. I was expecting to import the text elements at this stage at least.

![image](https://user-images.githubusercontent.com/29766214/107475852-aaa5cd00-6bd9-11eb-8dea-aefd8d2bdfb0.png)

4. Below is the diff. At this stage, PULL option is not available any more. It is treating as if text elements were deleted locally.

![image](https://user-images.githubusercontent.com/29766214/107475973-dd4fc580-6bd9-11eb-96df-7469579159d7.png)

5. Executed Force PULL and this time it has shown the program in inactive state however, still missing the text elements.

![image](https://user-images.githubusercontent.com/29766214/107476133-243dbb00-6bda-11eb-9fd0-a155d7d39403.png)

![image](https://user-images.githubusercontent.com/29766214/107476176-34ee3100-6bda-11eb-984a-f9a7f08b3ae6.png)

We are performing below manual tasks to bring the text elements.

1. After program created, fix the syntax error(s) by replacing with alternative objects
2. Stage the program file( /src/yprog1.prog.abap )  in different branch( fix ). This ensures syntax errors are fixed
3. Force pull the fix branch. This brings the text elements.

I would like to know if it is possible to bring the text elements( Text Symbols, Selection Text ) though syntax errors exists.

Regards,
Yellappa.

**Comment by larshp** [comment]
seems like a bug

@yellappam are you in the slack channel? https://abapgit-slackinviter.herokuapp.com I think it will be a lot easier for you to ensure consistency via [abaplint](https://abaplint.org/) before importing the objects into the ABAP system. This is also how we (typically) ensure that there are no syntax errors in abapGit

**Comment by yellappam** [comment]
Yes, I am in slack. Are you suggesting to use abapLint before importing? I am not sure whether we can setup S/4HANA checks for missing standard objects. Any help is appreciated.

**Comment by larshp** [comment]
use https://docs.abapopenchecks.org/checks/86/ in the source system to fix as much as possible beforehand

**Comment by mbtools** [comment]
I can confirm this behaviour. I had one missing domain (doma) and pulling into a different system caused a chain reaction of inactive objects: inactive dtel, inactive structure, inactive table type, inactive intf, inactive prog... intf and prog are deserialized only partially and in a way that they can't be edited to make them consistent/active. Once I added the missing domain to the repo, everything worked well.

In general, at least some of this must be expected since in such a case the repo is missing a fundamental building block. We can make AG check every possible dependency. For migration to another platform like ERP to S/4HANA or on-prem to S/4HANA cloud, this is and always will be a challenge. We/you should expect help from SAP (!), not from AG.

However, there is room for improvement in AG. It should deserialize objects in a consistent but inactive state. This will take some time to fix.

Finally, there should be an error message in the log related to the activation. Did you check the log after the first pull?

**Comment by mbtools** [comment]
I found the root cause: In case of activation errors (in `ZCL_ABAPGIT_OBJECTS_ACTIVATION=>ACTIVATE_OLD`), we trigger an exception. This exception will lead to a `rollback work` and therefore all most deserialized changes are lost (not for DDIC since that uses mass activation). 

@larshp, we could `commit work` before calling `RS_WORKING_OBJECTS_ACTIVATE` or after but before raising the exception (or turn off the rollback). I'm not sure.

**Comment by larshp** [comment]
try commit work before calling RS_WORKING_OBJECTS_ACTIVATE?
