### ISSUE TITLE
User exit class is not applicable to standalone installation

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#4727]
Mainly because all definitions are missing. I attempted to implement the `pre_calculate_repo_status` in one of the clients and failed. But of course there are more examples. 

Ideas: the only idea that come to my mind is to have a separate (automatically updated) abapgit repository with relevant definitions only. So major interfaces (probably not all). Maybe potentially with some wrapper class that can create instances of some classes from abapgit_standalone.
Furthermore upon abapGit full package installation the code can check if such a package exists in the system and warn/block deployment.

**Comment by larshp** [comment]
will this one work,

```abap
* create class ZCL_ABAPGIT_USER_EXIT implementing ZIF_ABAPGIT_EXIT in following include,
* if using the development version of abapGit create a global class instead
* place the object in a different package than ZABAPGIT
INCLUDE zabapgit_user_exit IF FOUND.
```

**Comment by mbtools** [comment]
The following works well for me:

1. Implement `ZCL_ABAPGIT_USER_EXIT` as global class and test with dev version
2. Cut & paste complete code of  `ZCL_ABAPGIT_USER_EXIT` into include `ZABAPGIT_USER_EXIT` and change the beginning to a local class

```abap
CLASS zcl_abapgit_user_exit DEFINITION
  FINAL
  CREATE PUBLIC.
```

**Comment by sbcgua** [comment]
Hmmm, could work, but it's not the "proper" way. There should be a less hacky way. Also doesn't quite fit to my case. In additional ZCL_USER_EXIT I use https://github.com/sbcgua/abapgit_xml_stripper_plugin so I will have to move to include as well.

But thank for the option anyway :)

**Comment by larshp** [comment]
"proper", then why not install the full dev edition? Getting something in between standalone and full dev would seem hacky to me

**Comment by sbcgua** [comment]
client instance ... full install needs more negotiation, and strust certificates

**Comment by pokrakam** [comment]
The problem is the interface, so the solution is to remove it from the class. PR #4781 adds a proxy that 'adds' the interface back. 
It's still a bit hacky, but it can be implemented with relatively little effort. More importantly, it needs no further action for most abapGit updates, just paste the new version and go.

To implement a standalone exit we must de-interface the regular user exit: 
- Create class `zcl_abapgit_standalone_exit`
- Copy/paste definition(s) you need from [zif_abapgit_exit](https://github.com/abapGit/abapGit/blob/3c51772175ff645e5f3e01e0e0e19b86cd8700fa/src/zif_abapgit_exit.intf.abap) into the public section
- Adapt or create any necessary abapGit-specifics (data types, `zcx_abapgit_exception`)
- Implement the method(s)

The proxy will forward any exceptions raised by the methods to `zcx_abapgit_exception` and parameter types must be compatible.

If the solution is agreeable I'll add it to the docs too.

**Comment by larshp** [comment]
@sbcgua close?

**Comment by sbcgua** [comment]
I think, yes.
