### ISSUE TITLE
background mode: automatic pull

### ISSUE THREAD

**Issue by MaximShmyrev** [abapGit/abapGit#4822]
Hey,

I'm trying to configure automatic pull according to [documentation](https://docs.abapgit.org/other-background-mode.html) for background mode. That's the error I'm getting
![image](https://user-images.githubusercontent.com/35171795/120833223-34ebb580-c56a-11eb-9bc7-0610e02bc52d.png)

After debug session I see that exist check in code (and one of this check is 'transport required')
![image](https://user-images.githubusercontent.com/35171795/120833330-52208400-c56a-11eb-91dc-eb7f54b05c30.png)

if this check is 'true' and no TR number provided system give an exception
![image](https://user-images.githubusercontent.com/35171795/120833426-7714f700-c56a-11eb-848d-9e2ac738d98a.png)

But I didn't found an interface to provide this TR number, I tried Advanced - Add all objects to Transport, but this also didn't help. Is is a bug or I'm doing something wrong?

**Comment by mbtools** [comment]
It's missing functionality. It either should create a new transport each time or use an existing transport. Also should have an option to release the transport automatically. 

Feel free to add it :-)

**Comment by MaximShmyrev** [comment]
Thanks for answer. Yes, I can add this feature. Several questions to clarify:

1. I can look up if objects of current package (linked to repository) are locked in existing transports, what if two objects are locked in two different transports? Just take one of them?
2. Should I add element in interface to provide user possibility to choose:
- create new transport (will be created every time with background job pull and release automatically)
- use existing transport (will use every time the same TR without release)
3. I can debug to understand whole logic, but maybe there is some technical spec, that I can use during development.

Cheers

**Comment by mbtools** [comment]
1. Keep it simple. If any object is already locked in a transport, fail the process.
2. I like both options. How about we make "Create" and "Use Existing" a radiobutton group and "Release Transport" a checkbox?
3. Sorry, only doc is on docs.abapgit.org

Have a look at https://github.com/abapGit/CI/blob/main/src/zcl_abapgit_ci_repo.clas.abap. You can probably copy some of the transport related code.

**Comment by mbtools** [comment]
splitting objects of the same repo/package between different transports is not good practice. On import of the different transports you will likely get errors due to dependencies.

**Comment by frij-aws** [comment]
I think the best way to keep things in one transport would be to do what MaximShmyrev suggested and search for an existing transport which holds the modified objects. In an environment that is iterating quickly and doing nightly batch pulls, you would not want to have to release your existing transport every night (after all, in SAP a release means that your objects have passed unit test and are ready to go to the QA queue for integration testing).  

It would make sense to pull nightly into the same transport (as detected by the ABAPGIT background job); then when your project is tested and ready to go to QA you can release that transport.

**Comment by larshp** [comment]
nothing right or wrong here, all depends on how the team wants to work

but as a consequence of the above, then the code merged to main will not have been reviewed or tested?

**Comment by frij-aws** [comment]
The scenario I'm seeing is not a contributor, but a company consuming code from github (say one of the projects listed on dotabap.org, like asjson) and wants to be sure their DEV has the latest version while their internal invoice-to-JSON interface is being developed.  This is a case where ABAPGIT-as-background-job would be useful.  

In any case I think we can have several different transport-resolution options if there are other use cases that must abort the pull if objects are already in a transport, or split the objects between transports if circumstances demand.  There doesn't seem to be very high demand for background pulls so maybe MaximShmyrev and I are the only ones.

Since MaximShmyrev hasn't chimed in, maybe I'll take a whack at this myself.  I'm not sure I fully understand the UI code yet but the background processing and transport handling seem pretty straightforward, so I should be able to get some default transport handling in place without touching the UI and then we can add radiobuttons when more finesse is needed.

**Comment by mbtools** [comment]
No news. It's a missing feature. Feel free to create a PR. We will help validate and test it.

**Comment by githubramya51** [comment]
Hi guys, 

Is anybody working on this issue? The error seems be there still.
Thanks.

**Comment by mbtools** [comment]
assume no one working on it

**Comment by mbtools** [comment]
Closed by https://github.com/abapGit/abapGit/pull/5916

You can set a transport request (also works for customizing) in the local settings of your repo

![image](https://github.com/abapGit/abapGit/assets/59966492/f20bcc3a-5c42-47d2-89e2-9ac76ac3a5a0)
