### ISSUE TITLE
Unit testing and isolation: replace call to SVRS_COMPUTE_DELTA_REPS with custom code

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4893]
Replace call to function module `SVRS_COMPUTE_DELTA_REPS` with custom diff logic

This will make it possible to run unit tests on github actions, plus reduce dependencies to the standard system.

https://github.com/abapGit/abapGit/blob/main/src/utils/zcl_abapgit_diff.clas.abap

**Comment by mbtools** [comment]
Not so easy since behind the scenes it's a kernel call (so we can't copy code) but certainly doable

**Comment by larshp** [comment]
we cant copy copyrighted code anyhow, it has to be done from scratch

guess something like https://en.wikipedia.org/wiki/Longest_common_substring_problem

**Comment by FreHu** [comment]
Related: https://github.com/abapGit/abapGit/issues/2804

https://github.com/Lugriz/typescript-algorithms/tree/master/src/algorithms/sets/longest-common-subsequence

Something to think about: I wonder why you chose to transpile abap into js instead of js into abap, as transpiling trash abap will only get you trash js anyway. The other way around you could transpile useful libraries into the ecosystem or make it easier to write classes/ddic by writing them in js and transpiling the abap boilerplate.

**Comment by FreHu** [comment]
Then of course you transpile abaplint into abap to run it natively in code inspector

**Comment by larshp** [comment]
see https://github.com/larshp/abap-wasm

JS can run anywhere, ABAP almost nowhere

**Comment by larshp** [comment]
ok, closing

@mbtools can you open source your test code?

**Comment by mbtools** [comment]
How about this one?
https://github.com/Marc-Bernard-Tools/ABAP-Diff3

And a test class that compares my diff3 with `SVRS_COMPUTE_DELTA_REP`:
https://github.com/Marc-Bernard-Tools/ABAP-Diff3-Tests

It matches for the small test cases but there will be differences on more complex diffs, literally.
