### ISSUE TITLE
SAPGUI crashes when abapGit is started

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5109]
We have a very strange behavior at one of our customers. SAPGUI always crashes completely when abapGit (full report) is started. If we try to debug that is the last statement which is executed. Then SAPGUI closes completely without a message.
![grafik](https://user-images.githubusercontent.com/17437789/140515676-fd6e2b90-ebee-4873-8850-c1a49810f9ab.png)

There a some entries in syslog.
![grafik](https://user-images.githubusercontent.com/17437789/140515713-d51e446c-4ba5-4f03-9be3-36cce84e489c.png)
![grafik](https://user-images.githubusercontent.com/17437789/140515734-af5e05d6-6845-4aae-b862-3c9923e459d4.png)
![grafik](https://user-images.githubusercontent.com/17437789/140515739-869b7d06-08cf-430d-8723-44c3e31536f2.png)
![grafik](https://user-images.githubusercontent.com/17437789/140515741-82f3593d-7260-49f1-bdcc-196908a1f348.png)

SAPGUI 7.60 PL08 hotfix 1 is used. 
![grafik](https://user-images.githubusercontent.com/17437789/140515763-1d13f65f-59ee-4ff7-82f5-b953fdb4a247.png)

Access via webgui is working.

There is this SAP note describing the error as normal system behavior.
https://launchpad.support.sap.com/#/notes/2287447
![grafik](https://user-images.githubusercontent.com/17437789/140516544-a78cfabf-333e-4128-8d50-3c4f0239ee12.png)

Any ideas?

**Comment by mbtools** [comment]
I have not seen this before. The syslog entries seem to be a cause of the DIA workprocess dying since it's lost connection to the GUI session on the local machine.

More tests to narrow down the cause:
- Does it happen on other machines? 
- With other GUI versions (760 patch 13 is latest)? 

The call of selection screen will start the GUI HTML Control. Might be a corrupt control locally. If it's just this machine, do SAPGUI installation check, potentially uninstall/reinstall GUI. 

If it's company wide, might be network related blocking certain traffic. Test with SAPHTML_EVENTS_DEMO if the HTML Control works in general. 

Or it's the size/memory consumption of the big report. There might be settings limiting user memory.

**Comment by christianguenter2** [comment]
Same issue on other machines too. Same GUI version.
Will try to update GUI.

**Comment by mbtools** [comment]
did you get it working?

**Comment by christianguenter2** [comment]
No new from colleagues.

**Comment by mbtools** [comment]
close?

**Comment by christianguenter2** [comment]
No news. Closing.
