### ISSUE TITLE
Support for Objecttype: LIMU/ DOCU  "Documentation"

### ISSUE THREAD

**Issue by fischmir** [abapGit/abapGit#5196]
Hey,

as most of know, we can extend custom classes and programs with a documentation (Transaction se61).

Unfortunately, this type of object is not (yet?) supported. Is there any specific reason why? Do you think it could technically be implemented?

I would love to git these objects as well.

Thanks,
fischmir

**Comment by larshp** [comment]
abapGit bases it objects on R3TR level, the LIMU objects are included in the R3TR

which R3TR object type are you using?

**Comment by fischmir** [comment]
Not sure if I got your question right. This is what I see in an transport request:

![image](https://user-images.githubusercontent.com/29099751/145556420-0ebeceba-a5d4-4d36-9bc6-626005bf42c2.png)

**Comment by larshp** [comment]
creating a general text via SE61 is a R3TR DOCT object(which is supported), which object type does the LIMU DOCU listed above belong to?

![image](https://user-images.githubusercontent.com/5888506/145557328-88937930-d4da-4842-ae3d-8a30e4ce2770.png)

**Comment by flaiker** [comment]
I am guessing it's this:

![image](https://user-images.githubusercontent.com/5270359/145641325-4a716fdc-0bf6-4277-a57a-cd2669596efe.png)

I did a quick test and also wasn't able to get the documents serialized. The logic for it retrieves the lines and then discards them because the DOKSTATE isn't R (which seems to be saved but not actived) but A (saved and activated) for some reason.

![image](https://user-images.githubusercontent.com/5270359/145642930-73635d03-7908-4bb0-9081-079bb0daff3c.png)

Since we only serialize active versions this needs to be changed to 'A' I think:

https://github.com/abapGit/abapGit/blob/ce677e449ff4258dd00da720d6658fbfd65a5903/src/objects/oo/zcl_abapgit_oo_base.clas.abap#L169

**Comment by fischmir** [comment]
That looks promising. Would love to test it soon.

**Comment by fischmir** [comment]
Works perfectly, thank you!
