### ISSUE TITLE
Longtexts don't get deleted on pull

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#5202]
Local version of the program has documentation, remote doesn't. Pull does not delete the local version of the documentation.

I think it's because an update only occurs if there are longtexts serialized, subrc <> 0 should call DOCU_DEL or something:

https://github.com/abapGit/abapGit/blob/18c9b404f139266747313deb3249c4c8186e78d2/src/objects/texts/zcl_abapgit_longtexts.clas.abap#L174

**Comment by flaiker** [comment]
I am not quite sure how to handle possible translations here.

https://docs.abapgit.org/settings-local.html#serialize-main-language-only

Does that local setting also mean don't touch any translations on deserialize (except for when the object itself is completely deleted)? It doesn't make much sense otherwise in repos where you push and pull.

**Comment by mbtools** [comment]
Texts and translations are not handled consistently across object types. Here's how it should work, IMHO:

- serialize should include main language + all translations
- serialize should include a list of translation languages (i18n_langs)
- deserialize processes the list of translation languages (i18n_langs)

If "main language only" is set, then serialize and deserialize ignore all translations.

The question of what happens to languages that are maintained locally but not included remotely is an open issue. Let's say the repo provides English and German and you locally add French. I would be for keeping French on deserialize rather than deleting it.

PS: The new LXE approach provides more flexibility but is limited to PROG, FUGR currently (https://docs.abapgit.org/ref-translations.html).
