### ISSUE TITLE
WebGUI: Runtime Error ASSERTION_FAILED in zcl_abapgit_serialize

### ISSUE THREAD

**Issue by jdgx** [abapGit/abapGit#5224]
Hi all,

When trying to connect to an online repository via WebGUI, I get an `ASSERTION_FAILED` runtime error in `zcl_abapgit_serialize` (line 482, after the `Z_ABAPGIT_SERIALIZE_PARALLEL` function call in method `run_parallel`). `sy-subrc` has value 2 and `lv_msg` says "RFC task 2 already open".

Details:

- Happens only with the non-standalone abapGit via WebGUI. For the standalone version (no matter if SAPGUI or WebGUI) or in SAPGUI (no matter if standalone or not) the issue is not present.
- SAP_BASIS 757
- abapGit version 1.113.0

Any ideas?

Best,
Jonathan

**Comment by christianguenter2** [comment]
Can you try to disable parallel processing?
![grafik](https://user-images.githubusercontent.com/17437789/146351285-145802bc-0a12-41bc-8a93-e0792440b2bb.png)

**Comment by jdgx** [comment]
OK, with parallel processing disabled it's working.  For me this is OK right now. Just let me know if somebody wants to track the issue down and needs more information.

Thanks,
Jonathan

PS: Changing the setting itself for me works only in SAPGUI. When I "Save Settings" (see screenshot above), I get a new WebGUI screen within the existing WebGUI screen, but nothing is saved. But this is another topic...

**Comment by christianguenter2** [comment]
Yeah, let's keep the issue open. Btw. I don't have this issue in WebGUI when parallel processing is enabled.
WebGUI has several quircks...

**Comment by mbtools** [comment]
The standalone version does not run anything in parallel (since the function group is not part of it). 

WebGUI has known limitations (no popups, etc) so not something you should use on a regular basis. The issue with nested frames is known (https://github.com/abapGit/abapGit/issues/4433) and reproducible. Unfortunately, no workaround is available currently.

Back to your issue, the explanation for the error is in SAP Note [1060205](https://launchpad.support.sap.com/#/notes/1060205).   We will have to check the code to see if we handle the task names correctly.

**Comment by mbtools** [comment]
you are right, of course. i mixed up with plain web version (via sicf).

**Comment by mbtools** [comment]
I had a closer look. The error can indeed occur if there are resource issues. If there are not sufficient dialog processes available, then the following do-loop might try to call `Z_ABAPGIT_SERIALIZE_PARALLEL` several times using the same task name. This will lead to the "RFC task <task name> already open" error as described in Note 1060205.

Please check if #5269 prevents this error
