### ISSUE TITLE
gCTS-compatible Repositories

### ISSUE THREAD

**Issue by ThomasErgin** [abapGit/abapGit#5340]
ABAPGit repositories can currently not be processed with SAP gCTS and vice versa. So if you want to use both clients in a landscape, you would need to produce two different repositories for the same solution.

Last year I learned from an SAP consultant, that this might change. He mentioned a compatible repository format without going into details. Is anyone aware about that? Do you know about plans, enabling the ABAPGit for the gCTS repository type or vice versa? I would like to use whatever Git-Solution fits best for any of my SAP landscapes – but this would require compatible repository formats.

Cheers

Thomas

**Comment by larshp** [comment]
see https://github.com/SAP/abap-file-formats

recently CHKO and more was implemented in abapGit, https://github.com/abapGit/abapGit/pulls?q=is%3Apr+chko+is%3Aclosed

**Comment by larshp** [comment]
Do note how SAP chooses to deliver software, changes are delivered as latest release, and sometimes some things are downported.

So if the file format updates, you will have to upgrade your S/4 HANA system to the latest release, or wait for the next release, in order to have file format compatibility.

abapGit you just update, running on any 702+ system

**Comment by larshp** [comment]
@ThomasErgin did above help, can we close the issue?

**Comment by mbtools** [comment]
Let's be clear: there are no plans to make abapGit and gCTS compatible with each other.

We do have an informal agreement with SAP to support the ABAP file format (as mentioned above) but it is currently limited to a few, new object types. While those particular files could be considered compatible with gCTS, this is where the similarities end. 

Conclusion: for each development project you have to choose either abapGit or gCTS. They can co-exist on the same SAP system but you should not use them both for the same project.

**Comment by larshp** [comment]
its not a either or, use abapGit for development, and then gCTS or classic CTS can be used for deployment, after the development artifacts are in the dev system

**Comment by larshp** [comment]
the plan is to make abapGit compatible with https://github.com/SAP/abap-file-formats

**Comment by ThomasErgin** [comment]
Thank you for all the info

**Comment by wagener-mark** [comment]
> the plan is to make abapGit compatible with https://github.com/SAP/abap-file-formats

Is there a timeline for that?

**Comment by larshp** [comment]
well, for abapGit it will be one by one, over some time. The formats will be changed when no existing information is lost in the conversion, eg. as of now we cannot build CLAS+INTF+DOMA+TABL+DTEL because the definitions contain less information than what is in abapGit currently.

Pull requests are welcome to help the process along.

Note that you can update abapGit at any time on any system, and abapGit will always suggest staging the latest format while accepting old abapGit format.
