### ISSUE TITLE
Transport and TADIR manangement

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5552]
Currently, each object class is responsible for managing the TADIR entries and adding objects to transports. A majority of issues identified by CI tests were related to incorrect or missing transport and TADIR entries.

Suggestion: 

Move handling of transport and TADIR entries to the abapGit framework (`zcl_abapgit_objects`) 

Reasoning: 

abapGit works on object level (`R3TR`) and object selections are based on TADIR anyway. Therefore, the TADIR entries created during `zcl_abapgit_objects=>deserialize` should match and `TADIR_INSERT` should always be executed. 

Similarly for transportable packages, changed objects should be recorded for all objects using `CORR_INSERT`. 

The same way `zcl_abapgit_objects=>delete` should always call `CORR_INSERT` and `TADIR_DELETE`.

This change would simplify the object class implementations and also remove the need for the `DELETE_TADIR` metadata flag.

**Comment by flaiker** [comment]
I agree this would be nice to solve outside of the individual object handlers in a generic way. Mostly because a lot of the development happens in local packages or the developer edition systems without transport landscape so errors may happen quite easily. It's probably easier to always call these and silently fail if the TADIR / transport entry already exists if the object type API already handled these on its own rather than complicating things more with additional flags that may also be release / patch level dependent.

**Comment by mbtools** [comment]
AG2 will provide an opportunity to handle it generically. No plans to change it for AG1
