### ISSUE TITLE
CLAS,INTF: Descriptions for subcomponents are not treated by object handlers

### ISSUE THREAD

**Issue by crasovan** [abapGit/abapGit#5659]
Method- and event-parameters can have descriptions persisted in DB table SEOSUBCOTX.
In the class ZCL_ABAPGIT_OO_BASE the methods  READ_DESCRIPTIONS/ UPDATE_DESCRIPTIONS the DB table SEOSUBCOTX is not considered.  This class is used by CLAS/INTF object handlers ZCL_ABAPGIT_OBJECT_CLAS respective ZCL_ABAPGIT_OBJECT_INTF.

https://github.com/abapGit/abapGit/blob/8555d1a0da6400fc04dbb0e3851e69bf76e5b720/src/objects/oo/zcl_abapgit_oo_base.clas.abap#L149-L164

**Comment by mbtools** [comment]
already addressed in https://github.com/abapGit/abapGit/pull/5575 (but not completed yet)

**Comment by schneidermic0** [comment]
I just came across this issue.

@mbtools Are you sure this issue is addressed in #5575/#5373? 

As far as I can see the PR and the issue are related to SAPscript documentation for components (like attributes, methods, events). 

This issues is about descriptions (not documentation) for subcomponents like (method parameters, exceptions, event parameters) which needs to be read from/written to Class Builders SEO* tables.

**Comment by larshp** [comment]
#5575

**Comment by mbtools** [comment]
Closed by https://github.com/abapGit/abapGit/pull/5755
