### ISSUE TITLE
Version Numbers for abapGit and patches?

### ISSUE THREAD

**Issue by richardbruenning** [abapGit/abapGit#5760]
Hi,

I have seen that there are coding changes and fixes but no new version is released. This results in a unexpected state, abapGit could be version 1.116.0 on different system with the same version but different coding (aka different bugs).

To better know when to update abapGit locally, I wurd prefer that fixes would result in a new version.

Sample #5750 

Thx :)

**Comment by larshp** [comment]
as a user you choose what to install,

* you can choose to install the latest version from main, always getting the latest bugfixes
* one of the tagged versions, https://github.com/abapGit/abapGit/tags
* or pull a specific commit

**Comment by richardbruenning** [comment]
Hi,
I understand that, but we have the following scenario:

10 Dev ABAP Stacks with abapGit as Standalone Report installed 
Now I want to update the systems to the newest version if necessary 
So we check for the version in abapGit, as an example on one of our system at the moment it is 1.116.0 (Standalone Version) installed July 8, 2022, 8:28:37 AM.
But now if I look at the differences between my local version 1.116.0 and the 1.116.0 from github we have differences
![image](https://user-images.githubusercontent.com/107387496/190172339-eff3f6d1-bf3e-4076-8a19-872b5704a611.png)

So with every release (pull request is getting accpeted the version number should be counted up.

:) Just my wish

**Comment by mbtools** [comment]
I understand your requirement. However, we are not living in a world of `npm version patch`, `npm publish`, and automation you find on other platforms. 

If you always want "latest", then the proper way is to install the developer version (full repo) and set up a background process to update nightly. Set it and forget it 😄

**Comment by fabianlupa** [comment]
One approach is also to suffix the version constant with -main / -next or already count up with -preview or something directly after the commit with the tag (counting up doesn't really work with semver). Then at least you would be able to tell programmatically if the version is fixed or just a greater equals value.

The changelog feature has a somewhat similar issue, it shows changes you might already have installed some time ago because it's based on the version number changing.

Currently the only way to have the version number always be meaningful is to only pull tags as the user. Which is also fine but somewhat depends on the release frequency for it to be practical.

**Comment by richardbruenning** [comment]
> I understand your requirement. However, we are not living in a world of `npm version patch`, `npm publish`, and automation you find on other platforms.
> 
> If you always want "latest", then the proper way is to install the developer version (full repo) and set up a background process to update nightly. Set it and forget it 😄

Hi,

I also did try that but there are breaking changes which kills abapGit Dev Version self update some times because the DDIC is inconsitent and could not be actived any more. Just had this issue this week, I did usw the standalone version to update.

So I think the idea was comming across and I will close this question
