### ISSUE TITLE
CLIF: Crash with CX_OO_INVALID_SUBCOMPO_KIND in UPDATE_META (ZCL_ABAPGIT_OO_INTERFACE)

### ISSUE THREAD

**Issue by kjetil-kilhavn** [abapGit/abapGit#5836]
I have installed the latest stand-alone version in several systems where I work recently. Using the new stand-alone version I pulled the updates of the development version into a system which had a really old version of that (1.89.0).
During deserialization the report crashed due to uncaught exception of type CX_OO_INVALID_SUBCOMPO_KIND. The exception is raised in CL_OO_SECTION_SOURCE method REVERT_PARAMETERS (line 70) - but the last abapGit method in the call stack is UPDATE_META of ZCL_ABAPGIT_OO_INTERFACE and the crash occurs in the last statement; lo_update->revert_scan_result( ).

I've looked at it for some time now without figuring out why it crashes, and when I tried again the deserialization completed. So possibly reproducible, but probably not easy to reproduce.

The object being deserialized when the crash occurs is ZIF_ABAPGIT_COMPARATOR.
When the exception is raised the PARAMETER structure has the following values:

name | value
----|----
CLSNAME | ZIF_ABAPGIT_COMPARATOR
CMPNAME | COMPARE
SCONAME | II_REMOTE
VERSION | 1
LANGU | E
DESCRIPT | 
CMPTYPE | 0
MTDTYPE | 	0
EDITORDER | 1
DISPID | 0
AUTHOR | 
CREATEDON | 00000000
CHANGEDBY | 
CHANGEDON | 00000000
PARDECLTYP | 0
PARPASSTYP | 1
TYPTYPE | 3
TYPE | ZIF_ABAPGIT_XML_INPUT
TABLEOF | 
PARVALUE | 
PAROPTIONL | 
PARPREFERD | 
LOCKED |

**Comment by mbtools** [comment]
What's the SAP Basis release?

Ref:

https://github.com/abapGit/abapGit/blob/e4aeff4f048c4406076a8fb8011c58aec8d7a8d5/src/objects/oo/zcl_abapgit_oo_interface.clas.abap#L134

**Comment by kjetil-kilhavn** [comment]
Ah, sorry about that. This system is on 7.50 (and SP level 24).

**Comment by kjetil-kilhavn** [comment]
The error could possibly occur if ZIF_ABAPGIT_XML_INPUT had not been (fully) activated yet, but unfortunately I didn't dive deep down into the details before trying again.

**Comment by mbtools** [comment]
Not sure if you will be able to reproduce this again. 

Best approach if things are quite old is a uninstall and reinstall of the repo using the most current stand-alone program.

**Comment by kjetil-kilhavn** [comment]
Actually I reproduced it today when I pulled your branch "package-check".
We ran into the problem with an existing report being assigned to another package in the system today when we pulled some code that had been developed in a sandbox. 
We just fixed in manually in our development system so the developers could continue working, but I thought I would test #5805 for this in another sandbox system. You can imagine my surprise when I got this error again - which I can not recall ever seing before I reported it.

name | value
----|----
CLSNAME | ZIF_ABAPGIT_LONGTEXTS
CMPNAME | CHANGED_BY
SCONAME | RV_USER
VERSION | 1
LANGU | 
DESCRIPT | 
CMPTYPE | 1
MTDTYPE | 0
EDITORDER | 4
DISPID | 0
AUTHOR | 
CREATEDON | 00000000
CHANGEDBY | 
CHANGEDON | 00000000
PARDECLTYP | 3
PARPASSTYP | 0
TYPTYPE | 1
TYPE | XUBNAME
TABLEOF | 
PARVALUE | 
PAROPTIONL | 
PARPREFERD | 
LOCKED | 

More importantly, when I tried to pull again, I could reproduce the crash (twice after the initial crash, so I assume it can be reproduced at will). 

The exception object has the following short and long texts (message OO_SOURCE_BASED/019):
The sub component RV_USER cannot be converted to a Parameters
You tried to convert the sub component  to another kind.
System Response
The editor does not support a conversion of sub components to another kind (exception, parameter) within one activation step. The source is not stored in the system.
Procedure
Delete the old component
Save and activate the class or interface
Create the new
Procedure for System Administration

ZIF_ABAPGIT_LONGTEXTS is currently active in the system, but RV_USER has type SYUNAME.
However, ZCL_ABAPGIT_LONGTEXTS is empty:
 ```
class ZCL_ABAPGIT_LONGTEXTS definition
  public
  create private .

public section.
protected section.
private section.
ENDCLASS.



CLASS ZCL_ABAPGIT_LONGTEXTS IMPLEMENTATION.
ENDCLASS.
```

Still not sure what to make of this, but at least it seems to be consistently reproducible now.

**Comment by mbtools** [comment]
Let's start at the end of your comment: I believe, if an object is inactive, AG will not touch it. You will have to activate it, first, before AG will deserialize (overwrite) it again. In the current state, force activate the class or delete it.

`OO_SOURCE_BASED 019` was introduced with SAP Note (2166231)[https://launchpad.support.sap.com/#/notes/2166231] in 740 (looks like SAP is missing the English translation). It says the issue happens when a subcomponent is changed in a certain way. This usually should not happen in AG since we use prefixes, for example, changing from `exporting` to `returning` means the parameter becomes a different subcomponent (`ev_param` to `rv_param`). 

However, there was a change of `zif_abapgit_longtexts->changed_by` some months ago (https://github.com/abapGit/abapGit/commit/c3b99804868c44c1035057e2bacdc422f59c997b) where the referenced data element was changed for `rv_user`. This should not trigger this exception but it looks like it did. hmm. It's SAP code, so not sure if we can do much about it in AG. I will try to reproduce it, but won't spend too much time (unless this happens more frequently).

**Comment by mbtools** [comment]
I think the best we can do without rewriting the class serializer is to catch the error:
https://github.com/abapGit/abapGit/pull/5841
