### ISSUE TITLE
abap language version prevents import into older system

### ISSUE THREAD

**Issue by dominikpanzer** [abapGit/abapGit#5921]
hi team,
a database table has ABAP language version 5 assigned because it was originally developed in an ABAP steampunk environment. I can't import a function group into older systems because of this. but the table should (hopefully) be compatible with older ABAP versions. here's the demo repo / issue https://github.com/dominikpanzer/ABAP-Meterdata-Manager/issues/1 
import via online repository is not possible.
import via offline/zip is possible, but the function group will be skipped
![grafik](https://user-images.githubusercontent.com/54714566/206473997-cc2e3eb3-f395-46ac-b229-aa9463b9f4b5.png)

**Comment by larshp** [comment]
there is a long discussion at https://github.com/SAP/abap-file-formats/issues/44, my opinion is that it should not be part of the XML

try commenting the following line and check if it works,
![image](https://user-images.githubusercontent.com/5888506/206480025-7654f968-0f34-4527-8699-fed37eecd503.png)

**Comment by larshp** [comment]
or adjust the XML files manually to be "normal" unicode, which can be imported into both old systems and new Steaumpunk

**Comment by larshp** [comment]
tho, perhaps we should add a workaround here to have it default to a supported UCCHECK

**Comment by dominikpanzer** [comment]
ok. it's quite strange. the ABAP language version only exists for a DB-Tabe and ana table type, but not for the FM. ABAPGit imports both without problems. but not the FM. https://github.com/dominikpanzer/ABAP-Meterdata-Manager/search?q=language+version
The FM actually doesn't use the table-type or the db-table.

after reading the thread: it could also work if I just remove the XML-Tag from the objects? I'll try that. Thanks Lars!

**Comment by larshp** [comment]
Steampunk uses the UCCHECK field for storing the langauge version, see https://github.com/dominikpanzer/ABAP-Meterdata-Manager/blob/main/src/zbilling_functions.fugr.saplzbilling_functions.xml#L14

try setting it to `<UCCHECK>X</UCCHECK>`

**Comment by mbtools** [comment]
abapGit is not handling the language version consistently. for some objects the field is cleared (example DDLS and DDLX), for some it is serialized (PROG, CLAS, FUGR). Function group/modules have additional logic for includes:

https://github.com/abapGit/abapGit/blob/004885fcc0efd42ab1fdafcdf51c91e7fd0051d9/src/objects/zcl_abapgit_object_fugr.clas.abap#L543-L576

I missed the AFF discussion last year. The conclusion there looks ok to me (although it's still up to the object type implementation to include the version or not). AG doesn't follow this logic at the moment. 

I suggest centralizing the mapping logic in AG since it's now all over. Then add an exit so everyone can have their own release/repo/object-specific logic.

**Comment by mbtools** [comment]
Closing in favor of #6154
