### ISSUE TITLE
Reorg packages

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5942]
Bring a bit more order into the package hierarchy:

Object | OId Package | Suggested New Package
--- | --- | ---
zcl_abapgit_login_manager | UTILS | HTTP
zcl_abapgit_url | UTILS | HTTP
zcl_abapgit_field_rules | OBJECTS | OBJECTS_RULES
zif_abapgit_field_rules | OBJECTS | OBJECTS_RULES
zcl_abapgit_adt_link | UTILS | OBJECTS_JUMP
zcl_abapgit_gui_jumper | OBJECTS_CORE | OBJECTS_JUMP
zif_abapgit_gui_jumper | UI | OBJECTS_JUMP
zcl_abapgit_exit | ROOT | EXIT
zif_abapgit_exit | ROOT | EXIT
zcl_abapgit_stage | ROOT | STAGE
zcl_abapgit_stage_logic | ROOT | STAGE
zif_abapgit_stage_logic | ROOT | STAGE
zcl_abapgit_merge | ROOT | STAGE
zif_abapgit_merge | ROOT | STAGE
zcl_abapgit_news | ROOT | UTILS
zcl_abapgit_version | ROOT | UTILS
zcl_abapgit_code_inspector | ROOT | INSPECT
zif_abapgit_code_inspector | ROOT | INSPECT

+ some better org of UI package which has too many classes

**Comment by larshp** [comment]
👍

**Comment by sbcgua** [comment]
Imho:
- zcl_abapgit_version is an util, it is not UI but actually a backend logic, doesn't touch user directly
- EXIT :+1:
- also news class is not UI either, it is parser. Maybe also an util ...
- UI package - yeah ... certainly needs some order. Here are some thoughts
  - core is abapgit agnostic, and I'd suggest keeping it this way and actually change nothing there
  - then, based on core there are some high level components, which are rendering related, maybe I'd call it UI_LIB
    - ex_viewer, buttons, chunk_lib (OMG this also should be cleaned up... :), component, hotkey_ctl, all HTML* classes, log_viwer, maybe somethign else
  - then, there are routing stuff: UI_ROUTING ?
    - router and service classes
  - then obviously pages: UI_PAGES ?
  - then some classes will probably stay in the root, because they do not match the categories above: factory, injector, popups (?), passdialog, frontends services

something like this

**Comment by sbcgua** [comment]
#5945 for my comment

**Comment by mbtools** [comment]
👍  for the UI changes. changed news + version to utils
