### ISSUE TITLE
Export a standard function group include?

### ISSUE THREAD

**Issue by Zeatynis** [abapGit/abapGit#5960]
Is it possible to export standard function group include? When I'm trying to export a standard function group that has the include I am insterested in the include itself is not exported. I need this to build dependencies to my project (abaplint doesn't know the standard subroutine I am using).

I need LSVIMFTX include of SVIM fugr.

**Comment by mbtools** [comment]
abapGit serializes only objects that are part of the SAP package assigned to the repository. It explicitly excludes the maintenance view includes since a) they belong to a different package, b) are generated, and c) are different in different systems/releases. 

https://github.com/abapGit/abapGit/blob/0a6248e9222af8b15d089ad670aeacb6072910bc/src/objects/zcl_abapgit_object_fugr.clas.abap#L655-L659

https://github.com/abapGit/abapGit/blob/0a6248e9222af8b15d089ad670aeacb6072910bc/src/objects/zcl_abapgit_object_fugr.clas.abap#L693-L696

If you remove some of these `if` statements, then it should serialize the includes, too. 

However, I suggest to exclude these function groups from abaplint altogether. I would try to avoid any such dependencies in my code as well. (Exception: you are extending the maintenance view with your own code).

**Comment by Zeatynis** [comment]
Ok, that makes sense. I was having this issue because I had a mistake in abaplint configuration. I didn't set the **skipGeneratedFunctionGroups** to true. I had thought I did this set to true but I didn't.
