### ISSUE TITLE
Refactor: Move `register_event_handler` to GUI component

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6049]
Currently, pages based on HOC register themselves during `render` using

```abap
gui_services( )->register_event_handler( me ).
```

Suggest moving `register_event_handler` to `zcl_abapgit_gui_component` and auto register pages similar to `register_hotkeys`.

Does that make sense @sbcgua ?

**Comment by sbcgua** [comment]
- Generally: self registering is good. I don't think we'll have a real case of a component that can but don't want to be registered
- But I don't understand which part of the `gui_component` will do the auto registration ? Nothing is automatically called there ?
- Or do you mean just as a shortcut ? a method that will literally test if the class (the sub-class!) has `zif_abapgit_gui_event_handler` and if yes, then call `gui_services( )->register_event_handler( me )` ? So that the real component still must call the method but a shorter one ?

**Comment by sbcgua** [comment]
... just thoughts ... what if the HOC tries to assign the component to `ref to gui_component` and (if successful) calls something like `prerender`. And the `prerender` (implemented in `gui_component`) auto calls `register_hotkeys` and `register_event_handler`, which by the way may become private with this scheme. In light of #6048, if all pages are components, then it may make sense. 

However needs some more thinking, because theoretically (and even desirably), components are not only pages. But they can be lower level components too. E.g. toolbar, or table control ...

just thoughts ...

**Comment by sbcgua** [comment]
I'll try to have a deeper look during the weekend
