### ISSUE TITLE
Missing authorization group

### ISSUE THREAD

**Issue by mssoftag** [abapGit/abapGit#6109]
- missing authorization group
The Authorization Group in Reports wer not transferred to the local system.
What can I do?
![image](https://user-images.githubusercontent.com/126463259/221892901-bb782a21-5458-48f3-9c7b-d226bc85de57.png)
![image](https://user-images.githubusercontent.com/126463259/221894303-e7f63fc8-764f-4df8-8187-59fe39d59824.png)

_Originally posted by @michasfer in https://github.com/abapGit/abapGit/issues/6104#issuecomment-1448345346_

**Comment by AndreaBorgia-Abo** [comment]
Ok, we tested once more like this:
* new package created
* one report created, with existing authorization group
* all staged and pushed
* checked in our internal gitea instance that the xml indeed shows a "SUCU" entry but no standalone SUCU file (was this what you meant by "[generic class](https://github.com/abapGit/abapGit/issues/6104#issuecomment-1448882939)"? @mbtools )
* deleted the package from the system but left the authorization group in place (in table TGTP)
* recreated online package, pulled all objects
* found that the authorization group entry is not carried over from the repository to the report properties

This time we used our internal gitea, the screenshot above however refers to an earlier test with a private repository that has since been deleted.

**Comment by mbtools** [comment]
I checked and `SUCU` is for table maintenance (table TBRG_AUTH). Auth groups for programs are customizing. You can try to use a BC set or the AG data feature:

![image](https://user-images.githubusercontent.com/59966492/222129855-c117c320-83c7-4792-89cd-d0735f3eb36a.png)

![image](https://user-images.githubusercontent.com/59966492/222129912-f721058a-c71c-4f0b-a9cb-442ccf885e78.png)

![image](https://user-images.githubusercontent.com/59966492/222130049-ec6961cb-5bda-4043-85bf-3a4b1c5daa5d.png)

To persist the data during pull, you need the following addition:

```abap
CLASS zcl_abapgit_repo.
...
  METHOD zif_abapgit_repo~deserialize.
...
    " Deserialize data (no save to database, just test for now)
    lt_result = zcl_abapgit_data_factory=>get_deserializer( )->deserialize(
      ii_config  = get_data_config( )
      it_files   = get_files_remote( ) ).

   " Persist data
   zcl_abapgit_data_factory=>get_deserializer( )->actualize( lt_result ).   "<<< INSERT
```

PS: Generic class was referring to `ZCL_ABAPGIT_OBJECTS_GENERIC` (used by `ZCL_ABAPGIT_OBJECT_SUCU`)

**Comment by mssoftag** [comment]
@mbtools 
Thx Marc

@AndreaBorgia-Abo 
Thx Andrea for your support

**Comment by AndreaBorgia-Abo** [comment]
@mbtools the data persistence could also be a nice addition but in this case it wasn't really need, do you think it would make sense to have it anyway?

**Comment by mbtools** [comment]
persisting data needs some restrictions. you don't want ppl to overwrite SAP tables for example. 

Something like preventing certain cases altogether and a "deserialize_check" for data with a warning popup 

Discuss here: https://github.com/abapGit/abapGit/issues/3441
