### ISSUE TITLE
Refactor: Repo checks and status 

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6178]
Goal: Separate repo (`$abapgit_repo`) and object logic (`$abapgit_objects`)

High-level:

Checks and status calculation before deserialize or delete are part of the repo logic. The user flow should be then be:

- Check objects and determine actions
- Get user decision and confirmation of actions
- Process actions

Note: Data (`tabu`) should be handled in the same way.

Some Details:

- [x] Rename `zcl_abapgit_file_status` to `zcl_abapgit_repo_status` 
  (#6413)
- [x] Move `zcl_abapgit_repo->status/mt_status/reset_status` to `zcl_abapgit_repo_status`
  (#6440)
- [ ] ~Rename `zcl_abapgit_objects_check` to `zcl_abapgit_repo_check` and move to `$abapgit_repo`
  Rename method `deserialize_check` to `check_objects`~
- [ ] ~Remove `zcl_abapgit_objects=>deserialize_checks` and call `zcl_abapgit_repo_check=>check_objects` from `zcl_abapgit_repo->deserialize_check`~
- [ ] ~Move `zcl_abapgit_repo->delete_check` to interface `zif_abapgit_repo->delete_check`~

**Comment by sbcgua** [comment]
Let's coordinate with #6107 (which is essentially status refactoring or even rewrite ...)

Also an opinion. Repo is overcrowded, too many responsibilities, I'd externalize as many functions as possible (long term). I particular: 
- `repo->status` is not a part of repo, it is an operation **over** a repo object (so should be smth like `zcl_abapgit_repo_status=>calculate( lo_repo )`)
- `delete_check` and any other `check` ... probaly also
- Generalizing, I'd say repo's responsibility is a container of files and objects

Also. Would be nice parallelize serialization and remote fetch. And also be able to serialize and yet display online repo if any error with fetch occured (or even forcefully skip the fetch to assess the changes). #3799, #3008. Theoretically it does not seem difficult. Fetch itself cannot be paralleled due to password request. But the **whole** serialization can be (not object by object like it is now). So: 1) start serialization thread (one ! the one to start other sub threads !), 2) fetch 3) wait for serialization "controller" thread. But now the `get_remote` and `get_local` are too coupled. In particular because of `status`. So something to consider. Not 100% sure how to design it, but have some faint ideas.

P.S. Naming, just imho "check" is veeeery generic term, unspecific and confusing, kind of "get", I'd pick a better name. At least "validate" or "consistency_check" or ...

**Comment by mbtools** [comment]
Refactor of status is done. Deferring to another time.
