### ISSUE TITLE
Direct connect to github.com:443 failed: NIECONN_REFUSED(-10)

### ISSUE THREAD

**Issue by danishsap** [abapGit/abapGit#6206]
Hi,

I am unable to connect to gihub.com from SAP S/4HANA 2021 private cloud edition.

![image](https://user-images.githubusercontent.com/8074045/230705433-1af5c13a-3cf4-4745-b2a4-cc4b5ef1f798.png)

![image](https://user-images.githubusercontent.com/8074045/230705484-22c29e5d-54a9-412e-b286-086d56389d95.png)

![image](https://user-images.githubusercontent.com/8074045/230705529-38f0e89d-9972-4c62-930c-e91719894fca.png)

![image](https://user-images.githubusercontent.com/8074045/230706170-3a4bd649-8d56-4130-9c80-589eb6280b91.png)

**Comment by larshp** [comment]
Hi Mr Danish, 
try checking 
![image](https://user-images.githubusercontent.com/5888506/230706642-b0ee50e1-00af-4e41-9577-ab0082aad31b.png)

However, it looks like a network issue to me, can the application server(s) access github.com?

**Comment by danishsap** [comment]
It is giving error also.

![image](https://user-images.githubusercontent.com/8074045/230706977-895dee47-eeee-462e-87d0-75b5ab00572d.png)

**Comment by larshp** [comment]
yea, looks like the application server cannot connect to github.com

check firewall and/or network setup

**Comment by bhasker-007** [comment]
Hi danishsap,

Can you share your solution if are you able to resolve this issue ?
we had a similar error when we try to call a rest api with token and key.

It worked absolutely fine when we run it on postman.

Thanks

**Comment by pokrakam** [comment]
The issue is with Private Cloud Edition internet connectivity is blocked by default and your provider needs to allow connections on a site/domain basis, so GitHub needs to be enabled.
Talk to your Basis team, they need to raise a service request with your service provider to open the firewall to allow connections to github.com and api.github.com
As you may have already experienced, competency of your provider may vary. In our case it took months. Tip: Set up an SM59 destination to GitHub as a test case otherwise you'll battle for weeks proving it's not abapGit. When SM59 destination test works, abapGit will work.
