### ISSUE TITLE
OTR texts not supported in SAP BTP (Cloud)

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#6747]
Hello, I've got one warning about OTR texts not supported when importing [abap2xlsx](https://github.com/abap2xlsx/abap2xlsx) to SAP BTP Cloud - SAP S/4HANA Public Cloud (pull via [abapGit Eclipse plugin](https://github.com/abapGit/eclipse.abapgit.org)):

abapGit repository:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/8db7c8ab-9ed1-4c84-b518-c183280d24c2)

Import log:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/cae614d6-c99c-4b7b-b74a-9bd33ee3f294)

Texts:
```
ZCX_EXCEL | CLAS | W | OTR (Online Text Respository) texts are not supported in SAP Cloud Platform, ABAP Environment
ZCX_EXCEL | CLAS | W | Object ZCX_EXCEL partly imported
```

Is it possible to enhance abapGit to not pull OTR texts and avoid these useless warnings, or are these warnings useful for some reason?

Thanks!
Sandra

**Comment by fabianlupa** [comment]
Well, you could refactor the exception class to not use OTR texts but T100 texts instead. The message seems important to me as the texts for the exception will not work after pull as they do not exist in the system?

**Comment by larshp** [comment]
in open source abapGit we cannot do much, SAP runs a fork which we have no control over

@ThomasPloski

**Comment by ThomasPloski** [comment]
Hi Sandra,

The reason why (S)OTR texts are not imported is just the missing possibility to edit such texts in ADT within BTP.

The warnings indicate that some parts of the to be imported objects of the linked repository are not fully imported. 

What would you except in such cases?

**Comment by sandraros** [comment]
@ThomasPloski Hi Thomas, I was stating that this OTR warning message is "useless" but in fact it's not, because the class must be adapted to ABAP Cloud, this warning means probably a syntax error after activating the class: `The use of Data Element SOTR_CONC is not permitted.` This is what happens to `ZCX_EXCEL`.

So, what I would expect now is a little bit different, e.g. to run automatically activation/syntax check after pulling (like Ctrl+Shift+F3 in ADT), in order to obtain a better import log (maybe having a second flag after "Pull after link"). Should I raise a ticket a SAP Support or somewhere else? Which software component is the abapGit Eclipse plugin?

Also, possibly, that would be nice to have a new feature in the ABAP objects import log, to provide long descriptions of the warnings/errors, to explain what to do, like the smart ones we have in ATC.

**Comment by ThomasPloski** [comment]
Hi @sandraros, 
Since BTP ABAP does not fully support all object usage/object types/ABAP language scope, the activation is not part of the a single import run. The idea is, that the user need to execute the syntax check and/or activation step to evaluate whether the imported objects fulfill the BTP ABAP restrictions. 
I will take the point regarding providing long descriptions for entries of type info/warning/error in the object log, so that the user will get more (context) information for each entry.

**Comment by mbtools** [comment]
It's an exception class ie code generated by SAP. I would expect that importing regenerates the code and puts it to a working state.

**Comment by fabianlupa** [comment]
> It's an exception class ie code generated by SAP.

You cannot create such classes or maintain the texts in ADT even onpremise so to me migrating to the T100 based approach still seems like the logical step.

**Comment by mbtools** [comment]
Any guess on how many exception classes with OTR exist in the world? Of course we can say to everyone, "just convert them manually" no big deal... or someone with three letters offers an automated solution (it's my #1 pet peeve that it always seems to be an afterthought on how to get from A to B rather than building the bridge first, then announce there's something new /rant)

**Comment by mbtools** [comment]
This needs to be addressed by SAP. Closing
