### ISSUE TITLE
Let's make a distinction between "Global Settings" and "Repository Settings".

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6758]
Dear abapGit Team,

 I've noticed that there is currently a lack of distinction between "Global Settings" and "Repository Settings." Both are currently presented under the generic label "Settings", which can lead to confusion. Additionally, upon pressing the F1 key (Command Palette), both settings are listed together, which further adds to the potential confusion.

To address this, I propose to introduce a distinction between "Global Settings" and "Repository Settings" within the user interface (refer to attached images).
        
These changes aim to enhance the user experience by making it more intuitive for everyone to navigate and understand the purpose of each group of settings.

Please let me know if you have any concerns or suggestions.

Thank you for your attention to this matter.

Best regards,

Francisco Milan.

![Global Settings and Repository Settings](https://github.com/abapGit/abapGit/assets/36721657/22ccd6f9-47c5-4f75-b77f-e0f81d899e46)
![Command - Global Settings](https://github.com/abapGit/abapGit/assets/36721657/08ab26ed-cd24-4ba0-9284-af876f4bacd6)
![Command - Repository Settings](https://github.com/abapGit/abapGit/assets/36721657/c533d9be-54f5-4f82-8890-8426b054c1be)

**Comment by christianguenter2** [comment]
Good improvement 👍 But why 3 pull requests? I'd suggest to consolidate them to one.

**Comment by francisco-milan** [comment]
Thanks a lot for the feedback Christian, I have applied the changes and now I have 1 pull request with 3 commits.

**Comment by mbtools** [comment]
Hmm. The top "settings" are for global and personal settings. Calling it "global settings" makes this more confusing. 

Maybe it should be "Config" but such changes need input from others

**Comment by francisco-milan** [comment]
Hi Marc,

    Thank you for sharing your thoughts on the current classification of settings in abapGit. I appreciate your input and agree that clarity in terminology is crucial for a better user experience.

I understand your concern about the term "Global settings" possibly causing confusion. Considering the various classifications like Global settings, Remote settings, Local settings, Personal settings, and Repository settings, I agree that a more standardized and precise naming convention could enhance clarity.

I would like to propose the idea of using terms like "abapGit settings", "Git settings" or "GitHub settings" to create clearer distinctions and avoid any potential confusion. This could provide a more straightforward and intuitive understanding of the purpose of each group of settings.

Best regards,

Francisco Milan.

**Comment by mbtools** [comment]
I don't think there's widespread confusion (or we would have more issues related to it). We have settings that apply to the abapGit setup:

![image](https://github.com/abapGit/abapGit/assets/59966492/b06b52f9-d640-4514-992e-8b15e19bdb17)

And settings that apply to a single repository:

![image](https://github.com/abapGit/abapGit/assets/59966492/88edc920-c0bd-430c-8f1f-c1d0819c0d30)

Both are well documented and after using abapGit for a little while, you know where to find certain settings. 

I don't think changing from "Global / Personal" to "General / User" will make a significant difference (but it would disrupt existing users). We use "Remote" instead of "git" or "github" since it's more general and applies to other types of repository provides like gitlab or a "zip" file (and there could be more in the future). 


I agree with you that identical menu items called "Settings" on the "Repository List" are confusing. That should be changed. 

It looks like you have a pretty wide screen. However, on smaller screens, there's limited space for the menu bars. So keeping it short is a preference. 

We could add a short description that shows when hovering over an item to help users.

Overall, I would keep the top item as "Settings" but add a hover hint. Change the second item to "Repo Settings" optionally with some hint.

**Comment by francisco-milan** [comment]
Hi Marc,

After considering your points, I would like to reiterate the proposal to change the top-level item from "Settings" to "Global Settings". This adjustment is particularly aligned with the landing page, where "Global Settings" is prominently displayed at the top. I believe this change will enhance clarity and maintain consistency for users navigating the settings.
![image](https://github.com/abapGit/abapGit/assets/36721657/9311f487-786f-458b-9624-d63a1fcd4c68)

In terms of space considerations, I understand the importance of keeping menu descriptions concise. However, upon comparing the two menus, "Top menu" and "Lower menu," it seems that the lower menu already occupies a significant amount of space with items such as "Filter," "Only Favorites," "Detail," and others. Therefore, changing the top-level item to "Global Settings" may not have a substantial impact on the overall space utilization.

![image](https://github.com/abapGit/abapGit/assets/36721657/89aa3b8a-b7e9-4c76-a8f3-fd237ff5317a)
We would have:
"abapgit Repository List Flow New Online New Offline Global Settings"
and
"Filter Only Favorites Detail Pull Stage Patch Diff Check Repo Settings More"

I fully support the proposal to change the second item to "Repo Settings" and the addition of hover hints for improved user guidance.

If there are further considerations or if you would like to discuss specific implementation details, please feel free to share your thoughts. I'm committed to collaborating and ensuring that these adjustments contribute positively to the overall user experience.

Thank you once again for your insights on this matter.

Best regards,

Francisco Milan.
