### ISSUE TITLE
Bug Report: Command Palette Alignment Issue on 'Repository List' Page.

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6798]
Dear abapGit Team,

I wanted to report a bug related to the alignment in the Command Palette (F1) on the "Repository List" page. As you can see in the image below, the items "Only Favorites" and "Display" are not aligned with the rest of the elements in the list. 

![image](https://github.com/abapGit/abapGit/assets/36721657/61eb9ba0-d433-495a-9420-059981592ffb)

This misalignment is a result of intentionally putting a white space in the Toolbar between the check mark icons and the corresponding text.

![image](https://github.com/abapGit/abapGit/assets/36721657/69d215e1-2b42-452c-9abe-36ec63a4bf18)

To improve the alignment, I initially proposed a solution by adjusting two lines of ABAP code within the Method "RENDER_FILTER_BAR", part of the Class "ZCL_ABAPGIT_GUI_PAGE_REPO_OVER".

![image](https://github.com/abapGit/abapGit/assets/36721657/c321ec83-be78-467d-a283-38b9a5b79957)

Instead of: (Line 23)
      iv_txt   = |<i id="icon-filter-favorite" class="icon icon-check { lv_icon_class }"></i> Only Favorites|
I suggested using: (Line 24)
      iv_txt  &nbsp; = &vert;&lt;i id=&quot;icon-filter-favorite&quot; class=&quot;icon icon-check &lbrace; lv_icon_class &rbrace;&quot;&gt;&lt;/i&gt;&vert; && &grave; &grave; && &vert;Only Favorites&vert;

And for the "Detail" item, instead of: (Line 28)
      iv_txt   = '<i id="icon-filter-detail" class="icon icon-check"></i> Detail'
I recommended using: (Line 29)
      iv_txt &nbsp;  = '&lt;i id="icon-filter-detail" class="icon icon-check"&gt;&lt;/i&gt; ' && &grave; &grave; && 'Detail'

And here's the result:

![image](https://github.com/abapGit/abapGit/assets/36721657/e010860b-f6eb-4d8a-ad44-93c97ef05886)
![image](https://github.com/abapGit/abapGit/assets/36721657/5c9bca9b-193d-4328-ae99-37ae00abbadd)

As highlighted in the two images above, this alternative successfully accomplishes the intended visual design for the Toolbar while ensuring proper alignment in the Command Palette. However, I acknowledge that there may be more optimal alternatives to consider. @sbcgua has suggested that it might be more appropriate to address this issue through adjustments in the CSS.

Given this recommendation, I am seeking guidance on how to proceed with investigating and implementing CSS adjustments to ensure proper alignment. As I am relatively new to this aspect, any insights or recommendations from someone experienced in CSS would be highly appreciated.

If there are specific CSS elements that I should focus on, or if there are alternative approaches to consider, your guidance would be invaluable.

Thank you for your time and assistance in addressing this matter. I look forward to your insights.

Best regards,

Francisco Milan.

**Comment by mbtools** [comment]
Neither. There are lots of other cases where commands are toggles with an icon in front of the text. We don't want to change all of these. 

The commands are collected in JS. That's were a the texts should be trimmed.

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/blob/0514b2df6267716136066bb5f87f3d166cf7ac1f/src/ui/zabapgit_js_common.w3mi.data.js#L2329

I guess "only favorites" and "details" is handled in the "other" section of this function

**Comment by sbcgua** [comment]
<img width="637" alt="image" src="https://github.com/abapGit/abapGit/assets/15635498/4bbd7c16-1464-4bf3-a1e1-47a639672df3">

To recap my comment in slack: formatting should be done with css, html is markup and structure. So those spaces are superfluous there. And it would be better to remove them. In css we need to increase `margin-right` or `padding-right` for that `icon`. Of course not for all icons, but for those in `repo-overview-toolbar`. So it should be something like:

```css
.repo-overview-toolbar .icon { padding-right: 2px }
```

Also I'd check the question mark icon earlier. It looks like it has some padding already. So that it does not conflict. Maybe the class should be `.repo-overview-toolbar .toolbar-light .icon { ...`.

Of course, it would be a patch. Long-term it's better to review labeled icon behavior in general ... and it will take more effort.

So, I actually agree with Marc's suggestion to trim text in JS. It is a more universal solution. And will work well for any other cases as well. Or maybe do both... (as the issue is well-spotted)

**Comment by francisco-milan** [comment]
The issue in the Command Palette is now fixed,

![image](https://github.com/abapGit/abapGit/assets/36721657/256e0a3c-5d20-4e57-83f7-51c2e8ea5c56)

I have adjusted the JavaScript to trim the white space on the left of "Oly Favorites" and "Details". The pull request #6799 is in draft version.

![image](https://github.com/abapGit/abapGit/assets/36721657/8466ce0d-c0de-4392-bd5a-fe6e1f841628)

If you want, I can also adjust the ABAP code before marking the PR ready for review, just let me know.



Thanks @mbtools and @sbcgua!
