### ISSUE TITLE
Different SICF paths for the same service in the source and target systems

### ISSUE THREAD

**Issue by sz3lbi** [abapGit/abapGit#6847]
**abapGit 1.127.0 - Developer Version**

I think this topic is related to the following issue: https://github.com/abapGit/abapGit/issues/4902

I have created some custom OData services in the source system. I would like to move a complete package that also contains these OData services to another system (both are S/4HANA).
Most of the objects from the package have been moved without any problems. However, I've noticed some problems related to these OData services:
1. Paths for these services in SICF are different after import, even though they are correct (not nested) in the `.sicf.xml` files. See the screenshots below for details.
Source system:
![Source System Path](https://github.com/abapGit/abapGit/assets/8168846/8a107ac1-cdba-4b4b-8181-054fd26bbe86)
![Source System URL (REMOTE XML in abapGit)](https://github.com/abapGit/abapGit/assets/8168846/414e8898-2518-466c-9d15-20a0b185288a)
Target system:
![Target System Path](https://github.com/abapGit/abapGit/assets/8168846/89823792-caaa-41d9-a3d3-49312bb61112)
Because of this, abapGit still shows me differences between the local state and the remote repository. However, when I try to pull again, I get a list of errors telling me that these services and some nodes already exist. So it sees differences that are there, but imports objects differently.
2. This is more of a suggestion than a serious issue. The service name does not change when you import SICF services. It still contains the name of the old system and the client at the beginning of the service name. I think this should be mapped so that it's not a mystery to SAP Basis how these names got into their system.

If you need any more information from me, I will update.

**Comment by mbtools** [comment]
What happens if you delete the service in the target system first? Does it pull correctly? Does it work correctly if you pull again?

When I look at https://github.com/abapGit-tests/SICF/tree/main/src, there are no system name or client number present. What's are the filenames?

Can you create a test case for this service in https://github.com/abapGit-tests/SICF_Odata, please?

**Comment by mbtools** [comment]
The filename for SICF should *not* match TADIR. 

Reason: The TADIR entry is based on the node id (icfparguid) which is generated by the system and therefore different in other systems. Instead of the node id, abapGit uses a filename based on a hash of the service URL:

https://github.com/abapGit/abapGit/blob/668da207aac4b0a0eba43c0ffc2e6f40e7ad43ce/src/objects/zcl_abapgit_object_sicf.clas.abap#L643

https://github.com/abapGit/abapGit/blob/668da207aac4b0a0eba43c0ffc2e6f40e7ad43ce/src/objects/zcl_abapgit_object_sicf.clas.abap#L206

If the filename in your repo matches TADIR, then you need to update this repo (with the current AG version). This will generate a new filename (based on the url-hash) and mark the old file for removal. Push both changes to the repo, so the SICF with the newf filename is stored and there won't be any diffs in abapGit.

Then try to pull again into your target system.

PS: In https://github.com/abapGit-tests/SICF_Odata, you can see this when you compare the main and test branches. Test has a filename based on the hash of `/sap/opu/odata/sap/S50200000000207/`.

**Comment by mbtools** [comment]
Thanks for the additional feedback. It looks like there are difference in the hash calculation.

Let's collect some details about the hashing algorithm and systems. I have included my results: 

- Run `ztest_abapgit_hash` in source and target systems for URL = /sap/opu/odata/sap/ZEWM_C_LAGP_SERVICE_V2/
  https://gist.github.com/mbtools/f87414014ae9c78f6f87e94a36ea7483

```
/sap/opu/odata/sap/ZEWM_C_LAGP_SERVICE_V2/
2F7361702F6F70752F6F646174612F7361702F5A45574D5F435F4C4147505F534552564943455F56322F
cb7024818b4b6c7c002a9e910d559a7e1bb0b4c1
```

- Run `zsysinfo` in source and target systems
   https://gist.github.com/mbtools/c4387a30556ac637eb28c9770ac30ad0

```
>> Application Server: vhcala4hci_A4H_00

Host name:                             VHCALA4HCI

Operating system:                      Linux
Operating system version:              SLES12
Operating platform:                    64-bit

SAP Kernel release:                    777_REL
SAP Kernel patch level:                534

Unicode:                               Yes
Endian:                                Little
```

What do you get (skip the server names)?

**Comment by mbtools** [comment]
Then your target system has the correct filename which is `/src/d50100000001335cb7024818b4b6c7c002a9e910.sicf.xml`.

So the issue is in your source system (and the repo). According to the test program, it also generates the correct hash. However, the serialized filename is different. This should not be the case since the test program uses the same logic as abapGit. 

Set a break-point in `zcl_abapgit_object_sicf=>get_hash_from_object`. What is the value of rv_hash in your source system?

**Comment by mbtools** [comment]
yes, that's it! let me see how we can solve this...

**Comment by mbtools** [comment]
Please test https://github.com/abapGit/abapGit/pull/6853. First, in the source system and update the repo (to include `icfaltnme_orig`). Then in the target, to pull the updated definition.

**Comment by mbtools** [comment]
I updated the class to include deserialize logic.

**Comment by mbtools** [comment]
great. new issue for srvb, please
