### ISSUE TITLE
No translations until LXE Approach is used. Translations created this way cannot be pulled.

### ISSUE THREAD

**Issue by sz3lbi** [abapGit/abapGit#7011]
**abapGit 1.129.0 - Developer Version** ([5dd4d83](https://github.com/abapGit/abapGit/tree/5dd4d83f3f1c257eea3818ed9e616d94f0b64e76))

Hello,  
I am having problems when trying to move objects with their translations using abapGit. There is a big chance that I am just doing things wrong, so please correct me if I am using some of the functionalities the wrong way.

1. **No translations until LXE Approach is used.**  
I have a message class with a single message and I add the Italian translation for this message. I also include this translation in TR using `SLXT`, but it should not matter.  
Then, I go to abapGit and in the repository settings put the `*` value in the field "Serialize Translations for Additional Languages" and leave the "Use Experimental LXE Approach for Translations" unchecked. When I try to stage, there is only a single file for this message class, but it contains no translations - only the English version of the message. Considering [the docs I read](https://docs.abapgit.org/user-guide/reference/translations.html), I would assume that this would be detected and added automatically - but maybe I just misinterpreted. The Italian version of the message is in the database table `T100`.
![Italian translation for the test message in the message class](https://github.com/user-attachments/assets/07bbf234-1f55-4ec6-a038-592025e58933)
![abapGit diff for the message class with no translations](https://github.com/user-attachments/assets/e4a586c5-bb37-40cf-8c81-a51d12893943)
Then I turn on the "Experimental LXE Approach for Translations" and i18n files appear. The one for the Italian language contains the correct text. There are other languages like Spanish or French, but the messages in them are **empty**.  
I can add the Italian translation and commit it correctly.
2. **Translations created this way cannot be pulled.**
After pushing the above changes to the repository, I remove objects from the system using abapGit (Advanced -> Remove Objects). Message class disappears from the package. Then I pull and message class is created. However, the Italian translation is not created in the system - abapGit still shows the differences between local and remote.  
![abapGit diff for the message class Italian translation after pulling the message class](https://github.com/user-attachments/assets/1cff66cb-3873-427a-b3b4-401d14b4e623)

If you have any questions, I will clarify. Thank you in advance for your help.

**Comment by sbcgua** [comment]
Hi sz3lbi,

The issue you describe in (1) can potentially happen. The "old" approach does not really know which languages are maintained, so it takes some high level object translation as a hint. E.g. in case of MSAG, do you have the italian translation of the message class itself? If not, try adding it. If I remember correctly, for MSAG, the serializer reads the translations of the class and based on languages there, then extracts the texts for messages.

(2) is a bit strange, but ! Try pulling it again. The LXE functionality cannot update translations until the object is activated and, if I remember correctly, when the object is new the sequence of activation may be improper due to technical reasons (a room for improvement for sure). So please try pulling again. If does not work, we'll dig deeper
