### ISSUE TITLE
Q: What shall happen during serialization when objects contain languages/translation that are not installed in system?

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#7019]
Method called here ignores languages that are not installed in the system, during serialization.
https://github.com/abapGit/abapGit/blob/1339a719695ef258aa151d87ec430c8c0b7a58cd/src/repo/zcl_abapgit_dot_abapgit.clas.abap#L207-L209

Pull https://github.com/albertmink/testing_intf_aff into system (with experimental settings X) that has `6N` not installed. Then all translations including `6N` will be deserialized, but will show as not in system, as `6N` is not serialized.

It feels odd that translation will be deserialized and exist on DBs, but abapGit shows a diff,
<img width="1305" alt="Screenshot 2024-08-21 at 10 23 13" src="https://github.com/user-attachments/assets/dbeb4baa-6f91-4727-b0cf-601cc432003e">

**Comment by mbtools** [comment]
Transports include all stored languages. AG should work the same way. If the repo is set to "main language only", then translations must be excluded. There are no tests for this so object serializers might not follow that properly. 

LXE feature provides some filtering of languages so that's different.
