### ISSUE TITLE
Link abapGit Repo dialog gets stuck when repo is added

### ISSUE THREAD

**Issue by prabhatpathania** [abapGit/abapGit#7117]
I am getting an (strange) error when I am trying to link my ABAP repo, that it is already in use.
Also, I cannot close the dialog after I get this error message. (I am using MacBook)

![Screenshot 2024-12-11 at 00 48 09](https://github.com/user-attachments/assets/697d71f4-a4c6-4726-8e91-7f5956a734a2)

When I try to use the top left close button, I get the message shown below.
At this stage, I can only close ADT and start it again.

![Screenshot 2024-12-11 at 00 51 25](https://github.com/user-attachments/assets/9ce9befb-b027-4e02-8b5d-78dac3df14c3)

**Comment by mbtools** [comment]
Sorry, same answer here. This is an SAP problem. Please open a ticket with SAP.

**Comment by pokrakam** [comment]
It's also partly a Java thing, Eclipse sometimes does a popup and if you click somewhere the popup gets hidden behind another window that you can't move out of the way because it's waiting for the popup input. 
On a Mac you can show all windows (swipe up with 4 fingers on the trackpad) and then click on the missing popup to bring it to foreground.
